# Figuring out how to automatically set up the metadata file needed for the process.py script

In [1]:
%cd ../..

/home/bhkuser/bhklab/katy/aaura-bench-preprocess

In [2]:
import pandas as pd
from pathlib import Path
from damply import dirs

In [3]:
dataset = "HCUCH_recist-dataset"
scan_dir_name = "images"
mask_dir_name = "masks"

In [ ]:
image_dir_path = dirs.RAWDATA / dataset / "images"

image_filepath_list = [i_path.relative_to(dirs.RAWDATA) for i_path in image_dir_path.rglob("*.nii.gz")]
image_filepath_list.sort()

In [ ]:
raw_aaura_metadata = {}

for idx, i_path in enumerate(image_filepath_list):
    raw_aaura_metadata[idx] = {
        'filepath': i_path.relative_to(dirs.RAWDATA),
        'source_id': f"{dataset}_{i_path.stem[0:3]}"
    }

    # rel_path = i_path.relative_to(dirs.RAWDATA)

In [12]:
raw_aaura_metadata_df = pd.DataFrame.from_dict(raw_aaura_metadata, orient='index')
raw_aaura_metadata_df.sort_values('source_id')

,filepath,source_id
28,HCUCH_recist-dataset/images/abdomen/train/imag...,HCUCH_recist-dataset_001
50,HCUCH_recist-dataset/images/abdomen/train/mask...,HCUCH_recist-dataset_001
100,HCUCH_recist-dataset/images/thorax/train/masks...,HCUCH_recist-dataset_001
84,HCUCH_recist-dataset/images/thorax/train/image...,HCUCH_recist-dataset_001
29,HCUCH_recist-dataset/images/abdomen/train/imag...,HCUCH_recist-dataset_002
...,...,...
48,HCUCH_recist-dataset/images/abdomen/train/imag...,HCUCH_recist-dataset_037
99,HCUCH_recist-dataset/images/thorax/train/image...,HCUCH_recist-dataset_037
115,HCUCH_recist-dataset/images/thorax/train/masks...,HCUCH_recist-dataset_037
71,HCUCH_recist-dataset/images/abdomen/train/mask...,HCUCH_recist-dataset_044
49,HCUCH_recist-dataset/images/abdomen/train/imag...,HCUCH_recist-dataset_044

In [41]:
series_metadata_file = dirs.RAWDATA / dataset / "metadata" / "series.json"

series_metadata_df = pd.read_json(series_metadata_file, orient='records')
series_metadata_df.sort_values('patient_id', ignore_index=True, inplace=True)
series_metadata_df.head()

,id,region,uuid,study_uuid,study_date,patient_id,slice_thickness,row_spacing,column_spacing,slices,rows,columns,slice_spacing
0,369,abdomen,1.3.12.2.1107.5.1.4.83504.30000023042612315883...,1.3.51.0.1.1.172.19.3.128.3187796.3187735,20230426,1,5.0,0.808594,0.808594,195,512,512,2.5
1,371,thorax,1.3.12.2.1107.5.1.4.83504.30000023042612315883...,1.3.51.0.1.1.172.19.3.128.3187796.3187735,20230426,1,1.5,0.710938,0.710938,331,512,512,1.0
2,5,thorax,1.3.12.2.1107.5.1.4.83504.30000022071212080050...,1.3.51.0.1.1.172.19.3.128.3051489.3051428,20220712,2,1.5,0.601562,0.601562,324,512,512,1.0
3,6,abdomen,1.3.12.2.1107.5.1.4.83504.30000022071212080050...,1.3.51.0.1.1.172.19.3.128.3051489.3051428,20220712,2,5.0,0.736328,0.736328,179,512,512,2.5
4,612,abdomen,1.3.12.2.1107.5.1.4.83504.30000021061509140333...,1.3.51.0.1.1.172.19.3.128.2857496.2857435,20210615,3,5.0,0.697266,0.697266,173,512,512,2.5

In [44]:
patient_metadata_file = dirs.RAWDATA / dataset / "metadata" / "patients.csv"
patient_metadata_df = pd.read_csv(patient_metadata_file)
patient_metadata_df.sort_values('patient_id', ignore_index=True, inplace=True)
patient_metadata_df.head()

,patient_id,subset,first_study_date,sex,age,diagnosis,histology,health_insurance
0,1,train,20230426,M,70,lung cancer,NaN,public
1,2,train,20220712,F,62,gastric cancer,NaN,uninsured
2,3,test,20210615,F,61,gallbladder cancer,Poorly Differentiated Adenocarcinoma with Sign...,uninsured
3,5,train,20210527,F,59,colon cancer,Moderately Differentiated Adenocarcinoma,uninsured
4,7,train,20210526,M,53,rectal cancer,Well Differentiated Adenocarcinoma,uninsured

In [61]:
all_metadata_df = pd.merge(patient_metadata_df, series_metadata_df, how = "inner", left_on = 'patient_id', right_on = 'patient_id')
all_metadata_df.rename(columns={'patient_id': 'patient_number', 'uuid': 'series_uid'}, inplace=True)
all_metadata_df.insert(loc=0, column='filename', value=all_metadata_df.apply(lambda row: f"{row.patient_number:03d}_{row.series_uid}.nii.gz", axis=1))
all_metadata_df.insert(loc=1, column='patient_id', value=all_metadata_df.apply(lambda row: f"{dataset}_{row.patient_number:03d}", axis=1))
all_metadata_df.insert(loc=0, column = 'filepath', value=all_metadata_df.apply(lambda row: Path(dataset, 'images', row.region, row.subset, scan_dir_name, row.filename), axis=1))

In [62]:
all_metadata_df

,filepath,filename,patient_id,patient_number,subset,first_study_date,sex,age,diagnosis,histology,...,series_uid,study_uuid,study_date,slice_thickness,row_spacing,column_spacing,slices,rows,columns,slice_spacing
0,HCUCH_recist-dataset/images/abdomen/train/imag...,001_1.3.12.2.1107.5.1.4.83504.3000002304261231...,HCUCH_recist-dataset_001,1,train,20230426,M,70,lung cancer,NaN,...,1.3.12.2.1107.5.1.4.83504.30000023042612315883...,1.3.51.0.1.1.172.19.3.128.3187796.3187735,20230426,5.0,0.808594,0.808594,195,512,512,2.5
1,HCUCH_recist-dataset/images/thorax/train/image...,001_1.3.12.2.1107.5.1.4.83504.3000002304261231...,HCUCH_recist-dataset_001,1,train,20230426,M,70,lung cancer,NaN,...,1.3.12.2.1107.5.1.4.83504.30000023042612315883...,1.3.51.0.1.1.172.19.3.128.3187796.3187735,20230426,1.5,0.710938,0.710938,331,512,512,1.0
2,HCUCH_recist-dataset/images/thorax/train/image...,002_1.3.12.2.1107.5.1.4.83504.3000002207121208...,HCUCH_recist-dataset_002,2,train,20220712,F,62,gastric cancer,NaN,...,1.3.12.2.1107.5.1.4.83504.30000022071212080050...,1.3.51.0.1.1.172.19.3.128.3051489.3051428,20220712,1.5,0.601562,0.601562,324,512,512,1.0
3,HCUCH_recist-dataset/images/abdomen/train/imag...,002_1.3.12.2.1107.5.1.4.83504.3000002207121208...,HCUCH_recist-dataset_002,2,train,20220712,F,62,gastric cancer,NaN,...,1.3.12.2.1107.5.1.4.83504.30000022071212080050...,1.3.51.0.1.1.172.19.3.128.3051489.3051428,20220712,5.0,0.736328,0.736328,179,512,512,2.5
4,HCUCH_recist-dataset/images/abdomen/test/image...,003_1.3.12.2.1107.5.1.4.83504.3000002106150914...,HCUCH_recist-dataset_003,3,test,20210615,F,61,gallbladder cancer,Poorly Differentiated Adenocarcinoma with Sign...,...,1.3.12.2.1107.5.1.4.83504.30000021061509140333...,1.3.51.0.1.1.172.19.3.128.2857496.2857435,20210615,5.0,0.697266,0.697266,173,512,512,2.5
5,HCUCH_recist-dataset/images/abdomen/test/image...,003_1.3.12.2.1107.5.1.4.83504.3000002108250932...,HCUCH_recist-dataset_003,3,test,20210615,F,61,gallbladder cancer,Poorly Differentiated Adenocarcinoma with Sign...,...,1.3.12.2.1107.5.1.4.83504.30000021082509324422...,1.3.51.0.1.1.172.19.3.128.2890383.2890322,20210825,5.0,0.677734,0.677734,175,512,512,2.5
6,HCUCH_recist-dataset/images/abdomen/test/image...,003_1.3.12.2.1107.5.1.4.83504.3000002110271233...,HCUCH_recist-dataset_003,3,test,20210615,F,61,gallbladder cancer,Poorly Differentiated Adenocarcinoma with Sign...,...,1.3.12.2.1107.5.1.4.83504.30000021102712332815...,1.3.51.0.1.1.172.19.3.128.2891111.2891050,20211027,5.0,0.628906,0.628906,177,512,512,2.5
7,HCUCH_recist-dataset/images/abdomen/train/imag...,005_1.3.12.2.1107.5.1.4.83504.3000002105271609...,HCUCH_recist-dataset_005,5,train,20210527,F,59,colon cancer,Moderately Differentiated Adenocarcinoma,...,1.3.12.2.1107.5.1.4.83504.30000021052716090067...,1.3.51.0.1.1.172.19.3.128.2847403.2847342,20210527,5.0,0.710938,0.710938,181,512,512,2.5
8,HCUCH_recist-dataset/images/abdomen/train/imag...,007_1.3.12.2.1107.5.1.4.83504.3000002110071227...,HCUCH_recist-dataset_007,7,train,20210526,M,53,rectal cancer,Well Differentiated Adenocarcinoma,...,1.3.12.2.1107.5.1.4.83504.30000021100712273932...,1.3.51.0.1.1.172.19.3.128.2890368.2890307,20211007,5.0,0.703125,0.703125,192,512,512,2.5
9,HCUCH_recist-dataset/images/abdomen/train/imag...,007_1.3.12.2.1107.5.1.4.83504.3000002108021212...,HCUCH_recist-dataset_007,7,train,20210526,M,53,rectal cancer,Well Differentiated Adenocarcinoma,...,1.3.12.2.1107.5.1.4.83504.30000021080212120090...,1.3.51.0.1.1.172.19.3.128.2879716.2879655,20210802,5.0,0.781250,0.781250,218,512,512,2.5
10,HCUCH_recist-dataset/images/abdomen/train/imag...,007_1.3.12.2.1107.5.1.4.83504.3000002105261220...,HCUCH_recist-dataset_007,7,train,20210526,M,53,rectal cancer,Well Differentiated Adenocarcinoma,...,1.3.12.2.1107.5.1.4.83504.30000021052612201586...,1.3.51.0.1.1.172.19.3.128.2847407.2847346,20210526,5.0,0.763672,0.763672,199,512,512,2.5
11,HCUCH_recist-dataset/images/thorax/train/image...,008_1.3.12.2.1107.5.1.4.83885.3000002208250748...,HCUCH_recist-dataset_008,8,train,20220825,M,59,gastric cancer,NaN,...,1.3.12.2.1107.5.1.4.83885.30000022082507483231...,1.3.51.0.1.1.172.19.3.128.3071604.3071543,20220825,1.5,0.556641,0.556641,355,512,512,1.0
12,HCUCH_recist-dataset/images/abdomen/train/imag...,008_1.3.12.2.1107.5.1.4.83504.3000002211291256...,HCUCH_recist-dataset_008,8,train,20220825,M,59,gastric cancer,NaN,...,1.3.12.2.1107.5.1.4.83504.30000022112912564272...,1.3.51.0.1.1.172.19.3.128.3112854.3112793,20221129,5.0,0.625000,0.625000,158,512,512,2.5
13,HCUCH_recist-dataset/images/abdomen/train/imag...,008_1.3.12.2.1107.5.1.4.83504.3000002210121320...,HCUCH_recist-dataset_008,8,train,20220825,M,59,gastric cancer,NaN,...,1.3.12.2.1107.5.1.4.83504.30000022101213201190...,1.3.51.0.1.1.172.19.3.128.3090470.3090409,20221012,5.0,0.671875,0.671875,162,512,512,2.5
14,HCUCH_recist-dataset/images/abdomen/train/imag...,008_1.3.12.2.1107.5.1.4.83885.3000002208250748...,HCUCH_recist-dataset_008,8,train,20220825,M,59,gastric cancer,NaN,...,1.3.12.2.1107.5.1.4.83885.30000022082507483231...,1.3.51.0.1.1.172.19.3.128.3071604.3071543,20220825,5.0,0.654297,0.654297,167,512,512,2.5
15,HCUCH_recist-dataset/images/thorax/train/image...,008_1.3.12.2.1107.5.1.4.83504.3000002211291256...,HCUCH_recist-dataset_008,8,train,20220825,M,59,gastric cancer,NaN,...,1.3.12.2.1107.5.1.4.83504.30000022112912564272...,1.3.51.0.1.1.172.19.3.128.3112854.3112793,20221129,1.5,0.544922,0.544922,379,512,512,1.0
16,HCUCH_recist-dataset/images/abdomen/train/imag...,008_1.3.12.2.1107.5.1.4.83504.3000002301170740...,HCUCH_recist-dataset_008,8,train,20220825,M,59,gastric cancer,NaN,...,1.3.12.2.1107.5.1.4.83504.30000023011707404892...,1.3.51.0.1.1.172.19.3.128.3142112.3142051,20230117,5.0,0.617188,0.617188,173,512,512,2.5
17,HCUCH_recist-dataset/images/thorax/test/images...,010_1.3.12.2.1107.5.1.4.83504.3000001712150708...,HCUCH_recist-dataset_010,10,test,20171215,M,67,melanoma,NaN,...,1.3.12.2.1107.5.1.4.83504.30000017121507082014...,1.3.51.0.1.1.172.19.3.128.2269090.2269029,20171215,1.5,0.740234,0.740234,341,512,512,1.0
18,HCUCH_recist-dataset/images/thorax/train/image...,012_1.3.12.2.1107.5.1.4.83504.3000001904151121...,HCUCH_recist-dataset_012,12,train,20190415,F,56,breast cancer,Invasive Ductal Breast Carcinoma,...,1.3.12.2.1107.5.1.4.83504.30000019041511214045...,1.3.51.0.1.1.172.19.3.128.2528604.2528543,20190415,1.5,0.566406,0.566406,311,512,512,1.0
19,HCUCH_recist-dataset/images/thorax/train/image...,012_1.3.12.2.1107.5.1.4.83504.3000001907031217...,HCUCH_recist-dataset_012,12,train,20190415,F,56,breast cancer,Invasive Ductal Breast Carcinoma,...,1.3.12.2.1107.5.1.4.83504.30000019070312170000...,1.3.51.0.1.1.172.19.3.128.2574060.2573999,20190703,1.5,0.585938,0.585938,317,512,512,1.0
20,HCUCH_recist-dataset/images/thorax/train/image...,012_1.3.12.2.1107.5.1.4.83504.3000001910301220...,HCUCH_recist-dataset_012,12,train,20190415,F,56,breast cancer,Invasive Ductal Breast Carcinoma,...,1.3.12.2.1107.5.1.4.83504.30000019103012204275...,1.3.51.0.1.1.172.19.3.128.2602174.2602113,20191030,1.5,0.625000,0.625000,289,512,512,1.0
21,HCUCH_recist-dataset/images/abdomen/test/image...,013_1.3.12.2.1107.5.1.4.83504.3000002106101431...,HCUCH_recist-dataset_013,13,test,20210610,M,58,gastric cancer,Papillary Adenocarcinoma,...,1.3.12.2.1107.5.1.4.83504.30000021061014315422...,1.3.51.0.1.1.172.19.3.128.2859703.2859642,20210610,5.0,0.671875,0.671875,203,512,512,2.5
22,HCUCH_recist-dataset/images/abdomen/test/image...,013_1.3.12.2.1107.5.1.4.83504.3000002108190521...,HCUCH_recist-dataset_013,13,test,20210610,M,58,gastric cancer,Papillary Adenocarcinoma,...,1.3.12.2.1107.5.1.4.83504.30000021081905213109...,1.3.51.0.1.1.172.19.3.128.2891124.2891063,20210819,5.0,0.712891,0.712891,189,512,512,2.5
23,HCUCH_recist-dataset/images/abdomen/test/image...,013_1.3.12.2.1107.5.1.4.83504.3000002110211236...,HCUCH_recist-dataset_013,13,test,20210610,M,58,gastric cancer,Papillary Adenocarcinoma,...,1.3.12.2.1107.5.1.4.83504.30000021102112360685...,1.3.51.0.1.1.172.19.3.128.2891127.2891066,20211021,5.0,0.742188,0.742188,184,512,512,2.5
24,HCUCH_recist-dataset/images/abdomen/test/image...,015_1.3.12.2.1107.5.1.4.83504.3000002001131352...,HCUCH_recist-dataset_015,15,test,20200113,M,64,bladder cancer,Plasmacytoid Urothelial Carcinoma,...,1.3.12.2.1107.5.1.4.83504.30000020011313523232...,1.3.51.0.1.1.172.19.3.128.2664062.2664001,20200113,5.0,0.763672,0.763672,189,512,512,2.5
25,HCUCH_recist-dataset/images/abdomen/test/image...,015_1.3.12.2.1107.5.1.4.83504.3000002002101209...,HCUCH_recist-dataset_015,15,test,20200113,M,64,bladder cancer,Plasmacytoid Urothelial Carcinoma,...,1.3.12.2.1107.5.1.4.83504.30000020021012090131...,1.3.51.0.1.1.172.19.3.128.2685398.2685337,20200210,5.0,0.763672,0.763672,196,512,512,2.5
26,HCUCH_recist-dataset/images/abdomen/test/image...,015_1.3.12.2.1107.5.1.4.83504.3000002004011418...,HCUCH_recist-dataset_015,15,test,20200113,M,64,bladder cancer,Plasmacytoid Urothelial Carcinoma,...,1.3.12.2.1107.5.1.4.83504.30000020040114181387...,1.3.51.0.1.1.172.19.3.128.2707708.2707647,20200401,5.0,0.742188,0.742188,190,512,512,2.5
27,HCUCH_recist-dataset/images/thorax/train/image...,016_1.3.12.2.1107.5.1.4.83504.3000002306121320...,HCUCH_recist-dataset_016,16,train,20230612,F,70,lung cancer,NaN,...,1.3.12.2.1107.5.1.4.83504.30000023061213202681...,1.3.51.0.1.1.172.19.3.128.3210299.3210238,20230612,1.5,0.572266,0.572266,375,512,512,1.0
28,HCUCH_recist-dataset/images/thorax/train/image...,016_1.3.12.2.1107.5.1.4.83504.3000002309140334...,HCUCH_recist-dataset_016,16,train,20230612,F,70,lung cancer,NaN,...,1.3.12.2.1107.5.1.4.83504.30000023091403342212...,1.3.51.0.1.1.172.19.3.128.3257700.3257639,20230914,1.5,0.580078,0.580078,345,512,512,1.0
29,HCUCH_recist-dataset/images/thorax/train/image...,016_1.3.12.2.1107.5.1.4.83504.3000002308081328...,HCUCH_recist-dataset_016,16,train,20230612,F,70,lung cancer,NaN,...,1.3.12.2.1107.5.1.4.83504.30000023080813283914...,1.3.51.0.1.1.172.19.3.128.3229685.3229624,20230808,1.5,0.585938,0.585938,327,512,512,1.0
30,HCUCH_recist-dataset/images/abdomen/test/image...,018_1.3.12.2.1107.5.1.4.83504.3000002105121112...,HCUCH_recist-dataset_018,18,test,20210513,M,65,colon cancer,Tubular Adenocarcinoma,...,1.3.12.2.1107.5.1.4.83504.30000021051211124165...,1.3.51.0.1.1.172.19.3.128.2844035.2843974,20210513,5.0,0.748047,0.748047,209,512,512,2.5
31,HCUCH_recist-dataset/images/thorax/train/image...,022_1.3.12.2.1107.5.1.4.83504.3000002103171411...,HCUCH_recist-dataset_022,22,train,20201029,M,64,colon cancer,Adenocarcinoma,...,1.3.12.2.1107.5.1.4.83504.30000021031714114711...,1.3.51.0.1.1.172.19.3.128.2781441.2781380,20210317,1.5,0.605469,0.605469,317,512,512,1.0
32,HCUCH_recist-dataset/images/abdomen/train/imag...,022_1.3.12.2.1107.5.1.4.83504.3000002103171411...,HCUCH_recist-dataset_022,22,train,20201029,M,64,colon cancer,Adenocarcinoma,...,1.3.12.2.1107.5.1.4.83504.30000021031714114711...,1.3.51.0.1.1.172.19.3.128.2781441.2781380,20210317,5.0,0.703125,0.703125,202,512,512,2.5
33,HCUCH_recist-dataset/images/abdomen/train/imag...,022_1.3.12.2.1107.5.1.4.83504.3000002101120208...,HCUCH_recist-dataset_022,22,train,20201029,M,64,colon cancer,Adenocarcinoma,...,1.3.12.2.1107.5.1.4.83504.30000021011202081810...,1.3.51.0.1.1.172.19.3.128.2781440.2781379,20210112,5.0,0.701172,0.701172,215,512,512,2.5
34,HCUCH_recist-dataset/images/thorax/train/image...,022_1.3.12.2.1107.5.1.4.83504.3000002101120208...,HCUCH_recist-dataset_022,22,train,20201029,M,64,colon cancer,Adenocarcinoma,...,1.3.12.2.1107.5.1.4.83504.30000021011202081810...,1.3.51.0.1.1.172.19.3.128.2781440.2781379,20210112,1.5,0.626953,0.626953,339,512,512,1.0
35,HCUCH_recist-dataset/images/abdomen/train/imag...,022_1.3.12.2.1107.5.1.4.83504.3000002010291642...,HCUCH_recist-dataset_022,22,train,20201029,M,64,colon cancer,Adenocarcinoma,...,1.3.12.2.1107.5.1.4.83504.30000020102916421550...,1.3.51.0.1.1.172.19.3.128.2759610.2759549,20201029,5.0,0.722656,0.722656,196,512,512,2.5
36,HCUCH_recist-dataset/images/thorax/train/image...,022_1.3.12.2.1107.5.1.4.83504.3000002010291642...,HCUCH_recist-dataset_022,22,train,20201029,M,64,colon cancer,Adenocarcinoma,...,1.3.12.2.1107.5.1.4.83504.30000020102916421550...,1.3.51.0.1.1.172.19.3.128.2759610.2759549,20201029,1.5,0.609375,0.609375,355,512,512,1.0
37,HCUCH_recist-dataset/images/abdomen/train/imag...,023_1.3.12.2.1107.5.1.4.83504.3000002112071209...,HCUCH_recist-dataset_023,23,train,20210729,F,74,colon cancer,Tubular Adenocarcinoma,...,1.3.12.2.1107.5.1.4.83504.30000021120712090076...,1.3.51.0.1.1.172.19.3.128.2949028.2948967,20211207,5.0,0.625000,0.625000,170,512,512,2.5
38,HCUCH_recist-dataset/images/abdomen/train/imag...,023_1.3.12.2.1107.5.1.4.83504.3000002107291221...,HCUCH_recist-dataset_023,23,train,20210729,F,74,colon cancer,Tubular Adenocarcinoma,...,1.3.12.2.1107.5.1.4.83504.30000021072912214330...,1.3.51.0.1.1.172.19.3.128.2882759.2882698,20210729,5.0,0.697266,0.697266,167,512,512,2.5
39,HCUCH_recist-dataset/images/abdomen/train/imag...,023_1.3.12.2.1107.5.1.4.83504.3000002111031238...,HCUCH_recist-dataset_023,23,train,20210729,F,74,colon cancer,Tubular Adenocarcinoma,...,1.3.12.2.1107.5.1.4.83504.30000021110312383749...,1.3.51.0.1.1.172.19.3.128.2930865.2930804,20211103,5.0,0.673828,0.673828,162,512,512,2.5
40,HCUCH_recist-dataset/images/abdomen/train/imag...,024_1.3.12.2.1107.5.1.4.83504.3000002012161141...,HCUCH_recist-dataset_024,24,train,20201216,F,75,gastric cancer,Poorly Differentiated Adenocarcinoma,...,1.3.12.2.1107.5.1.4.83504.30000020121611411612...,1.3.51.0.1.1.172.19.3.128.2780383.2780322,20201216,5.0,0.744141,0.744141,183,512,512,2.5
41,HCUCH_recist-dataset/images/abdomen/train/imag...,025_1.3.12.2.1107.5.1.4.83504.3000002303171319...,HCUCH_recist-dataset_025,25,train,20221220,F,65,gallbladder cancer,NaN,...,1.3.12.2.1107.5.1.4.83504.30000023031713195745...,1.3.51.0.1.1.172.19.3.128.3169154.3169093,20230317,5.0,0.828125,0.828125,185,512,512,2.5
42,HCUCH_recist-dataset/images/abdomen/train/imag...,025_1.3.12.2.1107.5.1.4.83885.3000002212201238...,HCUCH_recist-dataset_025,25,train,20221220,F,65,gallbladder cancer,NaN,...,1.3.12.2.1107.5.1.4.83885.30000022122012381826...,1.3.51.0.1.1.172.19.3.128.3128024.3127963,20221220,5.0,0.699219,0.699219,192,512,512,2.5
43,HCUCH_recist-dataset/images/abdomen/train/imag...,025_1.3.12.2.1107.5.1.4.83504.3000002302061319...,HCUCH_recist-dataset_025,25,train,20221220,F,65,gallbladder cancer,NaN,...,1.3.12.2.1107.5.1.4.83504.30000023020613190381...,1.3.51.0.1.1.172.19.3.128.3145648.3145587,20230206,5.0,0.722656,0.722656,198,512,512,2.5
44,HCUCH_recist-dataset/images/thorax/test/images...,028_1.3.12.2.1107.5.1.4.83504.3000002107191151...,HCUCH_recist-dataset_028,28,test,20210514,F,37,colon cancer,Adenocarcinoma,...,1.3.12.2.1107.5.1.4.83504.30000021071911510369...,1.3.51.0.1.1.172.19.3.128.2870470.2870409,20210719,1.5,0.527344,0.527344,282,512,512,1.0
45,HCUCH_recist-dataset/images/abdomen/test/image...,028_1.3.12.2.1107.5.1.4.83504.3000002107191151...,HCUCH_recist-dataset_028,28,test,20210514,F,37,colon cancer,Adenocarcinoma,...,1.3.12.2.1107.5.1.4.83504.30000021071911510369...,1.3.51.0.1.1.172.19.3.128.2870470.2870409,20210719,5.0,0.599609,0.599609,188,512,512,2.5
46,HCUCH_recist-dataset/images/abdomen/test/image...,028_1.3.12.2.1107.5.1.4.83504.3000002105141240...,HCUCH_recist-dataset_028,28,test,20210514,F,37,colon cancer,Adenocarcinoma,...,1.3.12.2.1107.5.1.4.83504.30000021051412400662...,1.3.51.0.1.1.172.19.3.128.2843215.2843154,20210514,5.0,0.591797,0.591797,175,512,512,2.5
47,HCUCH_recist-dataset/images/thorax/test/images...,028_1.3.12.2.1107.5.1.4.83504.3000002105141240...,HCUCH_recist-dataset_028,28,test,20210514,F,37,colon cancer,Adenocarcinoma,...,1.3.12.2.1107.5.1.4.83504.30000021051412400662...,1.3.51.0.1.1.172.19.3.128.2843215.2843154,20210514,1.5,0.525391,0.525391,333,512,512,1.0
48,HCUCH_recist-dataset/images/thorax/test/images...,030_1.3.12.2.1107.5.1.4.83885.3000002305221222...,HCUCH_recist-dataset_030,30,test,20230321,M,57,rectal cancer,Tubular Adenocarcinoma,...,1.3.12.2.1107.5.1.4.83885.30000023052212224943...,1.3.51.0.1.1.172.19.3.128.3190620.3190559,20230522,1.5,0.630859,0.630859,381,512,512,1.0
49,HCUCH_recist-dataset/images/thorax/test/images...,030_1.3.12.2.1107.5.1.4.83504.3000002303211231...,HCUCH_recist-dataset_030,30,test,20230321,M,57,rectal cancer,Tubular Adenocarcinoma,...,1.3.12.2.1107.5.1.4.83504.30000023032112314560...,1.3.51.0.1.1.172.19.3.128.3169329.3169268,20230321,1.5,0.689453,0.689453,359,512,512,1.0
50,HCUCH_recist-dataset/images/thorax/test/images...,030_1.3.12.2.1107.5.1.4.83504.3000002307201147...,HCUCH_recist-dataset_030,30,test,20230321,M,57,rectal cancer,Tubular Adenocarcinoma,...,1.3.12.2.1107.5.1.4.83504.30000023072011471461...,1.3.51.0.1.1.172.19.3.128.3229055.3228994,20230720,1.5,0.699219,0.699219,389,512,512,1.0
51,HCUCH_recist-dataset/images/thorax/train/image...,031_1.3.12.2.1107.5.1.4.83504.3000002308101318...,HCUCH_recist-dataset_031,31,train,20230810,M,68,lung cancer,NaN,...,1.3.12.2.1107.5.1.4.83504.30000023081013180867...,1.3.51.0.1.1.172.19.3.128.3238264.3238203,20230810,1.5,0.619141,0.619141,315,512,512,1.0
52,HCUCH_recist-dataset/images/thorax/train/image...,031_1.3.12.2.1107.5.1.4.83504.3000002310171328...,HCUCH_recist-dataset_031,31,train,20230810,M,68,lung cancer,NaN,...,1.3.12.2.1107.5.1.4.83504.30000023101713284842...,1.3.51.0.1.1.172.19.3.128.3268322.3268261,20231017,1.5,0.617188,0.617188,295,512,512,1.0
53,HCUCH_recist-dataset/images/abdomen/test/image...,035_1.3.12.2.1107.5.1.4.83504.3000002107071213...,HCUCH_recist-dataset_035,35,test,20210707,F,53,gastric cancer,Signet Ring Cell Adenocarcinoma,...,1.3.12.2.1107.5.1.4.83504.30000021070712131706...,1.3.51.0.1.1.172.19.3.128.2870375.2870314,20210707,5.0,0.664062,0.664062,173,512,512,2.5
54,HCUCH_recist-dataset/images/abdomen/test/image...,035_1.3.12.2.1107.5.1.4.83504.3000002109131213...,HCUCH_recist-dataset_035,35,test,20210707,F,53,gastric cancer,Signet Ring Cell Adenocarcinoma,...,1.3.12.2.1107.5.1.4.83504.30000021091312134713...,1.3.51.0.1.1.172.19.3.128.2891211.2891150,20210913,5.0,0.708984,0.708984,171,512,512,2.5
55,HCUCH_recist-dataset/images/abdomen/train/imag...,037_1.3.12.2.1107.5.1.4.83885.3000002302211215...,HCUCH_recist-dataset_037,37,train,20230221,M,64,lung cancer,NaN,...,1.3.12.2.1107.5.1.4.83885.30000023022112155417...,1.3.51.0.1.1.172.19.3.128.3156833.3156772,20230221,5.0,0.705078,0.705078,216,512,512,2.5
56,HCUCH_recist-dataset/images/thorax/train/image...,037_1.3.12.2.1107.5.1.4.83885.3000002302211215...,HCUCH_recist-dataset_037,37,train,20230221,M,64,lung cancer,NaN,...,1.3.12.2.1107.5.1.4.83885.30000023022112155417...,1.3.51.0.1.1.172.19.3.128.3156833.3156772,20230221,1.5,0.613281,0.613281,361,512,512,1.0
57,HCUCH_recist-dataset/images/abdomen/train/imag...,044_1.3.12.2.1107.5.1.4.83504.3000002301161753...,HCUCH_recist-dataset_044,44,train,20230116,F,70,ovarian cancer,NaN,...,1.3.12.2.1107.5.1.4.83504.30000023011617535917...,1.3.51.0.1.1.172.19.3.128.3140771.3140710,20230116,5.0,0.625000,0.625000,162,512,512,2.5

# Steps for preprocess metadata generation  
1. Load in any metadata files provided  
    a. merge everything
1. Make patient_id column with dataset and patient number
1. User specifies how to construct the filename and the filepath from columns in the metadata or other variables  
    a. Like scan directory name vs. mask directory name, since niftis are usually sorted by "images" and "masks" or "labels"
1. Make the filename column to be used to find the image and mask file

In [3]:
from typing import Optional, ClassVar
from pydantic import BaseModel, Field, field_validator, ValidationInfo

class NiftiDatasetConfig(BaseModel):
    """Configuration for nifti image dataset to create aaura index for."""

    datasource: str = Field(..., description="The source of the dataset (e.g. TCIA, PMCC)")
    dataset: str = Field(..., description="The name of the dataset (e.g. RADCURE)")
    patient_id_col: str = Field(default="patient_id", description="The name of the column in the metadata files that contains the patient ID")
    scan_name_pattern: str = Field(default="{patient_id}.nii.gz", description="The pattern to use for generating filenames in the index. Use {patient_id} and {series_uid} as placeholders for the patient ID and series UID, respectively.")
    mask_name_pattern : Optional[str] = Field(default=None, validate_default=True,description="The pattern to use for generating mask filenames in the index. Use {patient_id} and {series_uid} as placeholders for the patient ID and series UID, respectively.")
    scan_path_pattern: Optional[str] = Field(default="scans", description="The pattern to use for generating filepaths to the scan images starting after {datasource}_{dataset}/images.")
    mask_path_pattern: Optional[str] = Field(default="masks", description="The pattern to use for generating filepaths to the segmentation masks starting after {datasource}_{dataset}/images.")
    disease_site: Optional[str] = Field(default=None, description="The disease site of the dataset (e.g. lung)")
    metadata_files: Optional[list[str]] = Field(default=[], description="List of paths to metadata files to include in the index") 
    image_modality: Optional[str] = Field(default="CT", description="The modality of the images (e.g. CT)")
    drop_data: Optional[dict[str, list[str]]] = Field(default=None, description="Dictionary specifying any data to drop from the index (e.g. {'patient_id': ['TCGA-02-0047']})")
    anatomy_match_file: Optional[str] = Field(default=None, description="Path to a separate metadata file containing mappings of sources to anatomy labels, for use when dataset contains multiple other datasets with different disease sites.")

    @field_validator('scan_name_pattern')
    def validate_filename_pattern(cls, v):
        if ".nii.gz" not in v:
            return f"{v}.nii.gz"
        return v
    
    @field_validator('mask_name_pattern')
    def validate_maskname_pattern(cls, v, info: ValidationInfo):
        if v is not None and ".nii.gz" not in v:
            return f"{v}.nii.gz"
        elif v is None:
            v = info.data['scan_name_pattern']
        return v

    @field_validator('metadata_files')
    @classmethod
    def validate_metadata_files(cls, v: list[str], info: ValidationInfo):
        if not isinstance(v, list):
            raise ValueError("metadata_files must be a list")
        elif len(v) == 0:
            print("No metadata files specified. Attempting to find metadata files in expected location...")
            metadata_dir_path = dirs.RAWDATA / f"{info.data['datasource']}_{info.data['dataset']}/metadata"
            v = list(metadata_dir_path.glob(r"*.csv")) + list(metadata_dir_path.glob(r"*.json"))
            if len(v) == 0:
                raise ValueError(f"No metadata files found in expected location: {metadata_dir_path}")
            if info.data['anatomy_match_file'] is not None:
                v.drop(info.data['anatomy_match_file'], inplace=True)
        return v

In [5]:
recist_data_config = NiftiDatasetConfig(
    datasource="HCUCH",
    dataset="recist-dataset",
    scan_name_pattern="{patient_id:03d}_{series_uid}.nii.gz",
    scan_path_pattern="{region}/{subset}/images",
    mask_path_pattern="{region}/{subset}/masks",
    metadata_files=['patients.csv', 'series.json'],
    image_modality="CT")

recist_data_config

NiftiDatasetConfig(datasource='HCUCH', dataset='recist-dataset', patient_id_col='patient_id', scan_name_pattern='{patient_id:03d}_{series_uid}.nii.gz', mask_name_pattern='{patient_id:03d}_{series_uid}.nii.gz', scan_path_pattern='{region}/{subset}/images', mask_path_pattern='{region}/{subset}/masks', disease_site=None, metadata_files=['patients.csv', 'series.json'], image_modality='CT', drop_data=None, anatomy_match_file=None)

In [6]:
lesion_locator_config = NiftiDatasetConfig(
    datasource = "CVPR",
    dataset = "LesionLocator",
    patient_id_col = "File Name",
    scan_name_pattern="{patient_id}_0000.nii.gz",
    mask_name_pattern="{patient_id}.nii.gz",
    scan_path_pattern="images/{timepoint}/images",
    mask_path_pattern="masks/{timepoint}/labels",
    metadata_files = ["10_example_cases.csv"],
    image_modality = "CT",
    drop_data = {"Source": ['coronacases','NIH-LYMPH']},
    anatomy_match_file="dataset_anatomy_match.csv"
)

lesion_locator_config

NiftiDatasetConfig(datasource='CVPR', dataset='LesionLocator', patient_id_col='File Name', scan_name_pattern='{patient_id}_0000.nii.gz', mask_name_pattern='{patient_id}.nii.gz', scan_path_pattern='images/{timepoint}/images', mask_path_pattern='masks/{timepoint}/labels', disease_site=None, metadata_files=['10_example_cases.csv'], image_modality='CT', drop_data={'Source': ['coronacases', 'NIH-LYMPH']}, anatomy_match_file='dataset_anatomy_match.csv')

In [23]:
mama_mia_config = NiftiDatasetConfig(
    datasource='BCN-AIM',
    dataset='MAMA-MIA',
    patient_id_col = 'patient_id',
    scan_name_pattern="{patient_id}_0000.nii.gz",
    mask_name_pattern="{patient_id}.nii.gz",
    metadata_files = ['clinical_and_imaging_info.csv'],
    scan_path_pattern="scans/{patient_id}",
    mask_path_pattern="masks",
    image_modality="MR",
    disease_site='breast'
)

mama_mia_config

NiftiDatasetConfig(datasource='BCN-AIM', dataset='MAMA-MIA', patient_id_col='patient_id', scan_name_pattern='{patient_id}_0000.nii.gz', mask_name_pattern='{patient_id}.nii.gz', scan_path_pattern='scans/{patient_id}', mask_path_pattern='masks', disease_site='breast', metadata_files=['clinical_and_imaging_info.csv'], image_modality='MR', drop_data=None, anatomy_match_file=None)

In [24]:
config = mama_mia_config

metadata_df = pd.read_csv(dirs.RAWDATA / f"{config.datasource}_{config.dataset}" / "metadata" / config.metadata_files[0])

In [25]:
from imgtools.pattern_parser import PatternResolver

def image_path_resolver(metadata_row:pd.Series,
                        image_path_pattern:str,
                        image_file_pattern:str) -> str:
    
    filename_format = f"{image_path_pattern}/{image_file_pattern}"

    image_path_resolver = PatternResolver(filename_format)

    return image_path_resolver.resolve(metadata_row.to_dict())

In [26]:
metadata_df.apply(lambda row: image_path_resolver(row, config.scan_path_pattern, config.scan_name_pattern), axis=1)

0       scans/DUKE_001/DUKE_001_0000.nii.gz
1       scans/DUKE_002/DUKE_002_0000.nii.gz
2       scans/DUKE_005/DUKE_005_0000.nii.gz
3       scans/DUKE_009/DUKE_009_0000.nii.gz
4       scans/DUKE_010/DUKE_010_0000.nii.gz
                       ...
1501      scans/NACT_64/NACT_64_0000.nii.gz
1502      scans/NACT_65/NACT_65_0000.nii.gz
1503      scans/NACT_66/NACT_66_0000.nii.gz
1504      scans/NACT_67/NACT_67_0000.nii.gz
1505      scans/NACT_68/NACT_68_0000.nii.gz
Length: 1506, dtype: object

In [27]:
metadata_df.apply(
        lambda row: Path(f"{config.datasource}_{config.dataset}") / "images" / image_path_resolver(row, config.mask_path_pattern, config.mask_name_pattern), 
        axis = 1
        )

0       BCN-AIM_MAMA-MIA/images/masks/DUKE_001.nii.gz
1       BCN-AIM_MAMA-MIA/images/masks/DUKE_002.nii.gz
2       BCN-AIM_MAMA-MIA/images/masks/DUKE_005.nii.gz
3       BCN-AIM_MAMA-MIA/images/masks/DUKE_009.nii.gz
4       BCN-AIM_MAMA-MIA/images/masks/DUKE_010.nii.gz
                            ...
1501     BCN-AIM_MAMA-MIA/images/masks/NACT_64.nii.gz
1502     BCN-AIM_MAMA-MIA/images/masks/NACT_65.nii.gz
1503     BCN-AIM_MAMA-MIA/images/masks/NACT_66.nii.gz
1504     BCN-AIM_MAMA-MIA/images/masks/NACT_67.nii.gz
1505     BCN-AIM_MAMA-MIA/images/masks/NACT_68.nii.gz
Length: 1506, dtype: object

In [ ]:
from imgtools.pattern_parser import PatternResolver

pattern = config.scan_path_pattern

for sample_tuple in metadata_df.itertuples(index=False):

    scan_path_resolver = PatternResolver(filename_format=config.scan_path_pattern)
    scan_path = scan_path_resolver.resolve(sample_tuple._asdict())
    print(scan_path)

scans/DUKE_001
scans/DUKE_002
scans/DUKE_005
scans/DUKE_009
scans/DUKE_010
scans/DUKE_012
scans/DUKE_019
scans/DUKE_021
scans/DUKE_022
scans/DUKE_028
scans/DUKE_032
scans/DUKE_034
scans/DUKE_040
scans/DUKE_041
scans/DUKE_043
scans/DUKE_044
scans/DUKE_045
scans/DUKE_046
scans/DUKE_048
scans/DUKE_051
scans/DUKE_055
scans/DUKE_057
scans/DUKE_059
scans/DUKE_060
scans/DUKE_061
scans/DUKE_064
scans/DUKE_069
scans/DUKE_071
scans/DUKE_077
scans/DUKE_082
scans/DUKE_086
scans/DUKE_090
scans/DUKE_091
scans/DUKE_097
scans/DUKE_099
scans/DUKE_101
scans/DUKE_103
scans/DUKE_104
scans/DUKE_105
scans/DUKE_107
scans/DUKE_114
scans/DUKE_115
scans/DUKE_116
scans/DUKE_117
scans/DUKE_119
scans/DUKE_120
scans/DUKE_123
scans/DUKE_129
scans/DUKE_132
scans/DUKE_134
scans/DUKE_136
scans/DUKE_137
scans/DUKE_141
scans/DUKE_142
scans/DUKE_144
scans/DUKE_148
scans/DUKE_150
scans/DUKE_156
scans/DUKE_157
scans/DUKE_160
scans/DUKE_163
scans/DUKE_167
scans/DUKE_168
scans/DUKE_176
scans/DUKE_177
scans/DUKE_178
scans/DUKE_180
scans/DUKE_183
scans/DUKE_185
scans/DUKE_189
scans/DUKE_192
scans/DUKE_198
scans/DUKE_202
scans/DUKE_205
scans/DUKE_211
scans/DUKE_217
scans/DUKE_218
scans/DUKE_225
scans/DUKE_228
scans/DUKE_233
scans/DUKE_234
scans/DUKE_236
scans/DUKE_237
scans/DUKE_239
scans/DUKE_240
scans/DUKE_244
scans/DUKE_250
scans/DUKE_253
scans/DUKE_255
scans/DUKE_256
scans/DUKE_258
scans/DUKE_260
scans/DUKE_265
scans/DUKE_268
scans/DUKE_269
scans/DUKE_271
scans/DUKE_275
scans/DUKE_282
scans/DUKE_283
scans/DUKE_285
scans/DUKE_287
scans/DUKE_290
scans/DUKE_293
scans/DUKE_298
scans/DUKE_301
scans/DUKE_303
scans/DUKE_304
scans/DUKE_306
scans/DUKE_307
scans/DUKE_313
scans/DUKE_317
scans/DUKE_321
scans/DUKE_323
scans/DUKE_328
scans/DUKE_333
scans/DUKE_335
scans/DUKE_338
scans/DUKE_345
scans/DUKE_346
scans/DUKE_350
scans/DUKE_353
scans/DUKE_356
scans/DUKE_360
scans/DUKE_363
scans/DUKE_368
scans/DUKE_377
scans/DUKE_378
scans/DUKE_383
scans/DUKE_385
scans/DUKE_386
scans/DUKE_387
scans/DUKE_395
scans/DUKE_397
scans/DUKE_398
scans/DUKE_399
scans/DUKE_400
scans/DUKE_406
scans/DUKE_407
scans/DUKE_408
scans/DUKE_412
scans/DUKE_414
scans/DUKE_420
scans/DUKE_424
scans/DUKE_428
scans/DUKE_429
scans/DUKE_431
scans/DUKE_435
scans/DUKE_437
scans/DUKE_438
scans/DUKE_441
scans/DUKE_444
scans/DUKE_454
scans/DUKE_457
scans/DUKE_464
scans/DUKE_465
scans/DUKE_468
scans/DUKE_470
scans/DUKE_474
scans/DUKE_480
scans/DUKE_482
scans/DUKE_486
scans/DUKE_489
scans/DUKE_491
scans/DUKE_501
scans/DUKE_506
scans/DUKE_507
scans/DUKE_508
scans/DUKE_512
scans/DUKE_514
scans/DUKE_517
scans/DUKE_521
scans/DUKE_525
scans/DUKE_527
scans/DUKE_530
scans/DUKE_534
scans/DUKE_535
scans/DUKE_539
scans/DUKE_541
scans/DUKE_543
scans/DUKE_545
scans/DUKE_546
scans/DUKE_552
scans/DUKE_558
scans/DUKE_559
scans/DUKE_560
scans/DUKE_562
scans/DUKE_567
scans/DUKE_568
scans/DUKE_573
scans/DUKE_577
scans/DUKE_585
scans/DUKE_590
scans/DUKE_592
scans/DUKE_595
scans/DUKE_597
scans/DUKE_605
scans/DUKE_607
scans/DUKE_609
scans/DUKE_610
scans/DUKE_612
scans/DUKE_614
scans/DUKE_615
scans/DUKE_616
scans/DUKE_618
scans/DUKE_623
scans/DUKE_633
scans/DUKE_636
scans/DUKE_640
scans/DUKE_641
scans/DUKE_642
scans/DUKE_645
scans/DUKE_650
scans/DUKE_651
scans/DUKE_652
scans/DUKE_656
scans/DUKE_660
scans/DUKE_662
scans/DUKE_663
scans/DUKE_666
scans/DUKE_670
scans/DUKE_672
scans/DUKE_677
scans/DUKE_679
scans/DUKE_681
scans/DUKE_684
scans/DUKE_685
scans/DUKE_686
scans/DUKE_687
scans/DUKE_688
scans/DUKE_691
scans/DUKE_693
scans/DUKE_694
scans/DUKE_697
scans/DUKE_710
scans/DUKE_717
scans/DUKE_718
scans/DUKE_723
scans/DUKE_724
scans/DUKE_725
scans/DUKE_735
scans/DUKE_746
scans/DUKE_751
scans/DUKE_754
scans/DUKE_757
scans/DUKE_758
scans/DUKE_762
scans/DUKE_765
scans/DUKE_774
scans/DUKE_775
scans/DUKE_776
scans/DUKE_778
scans/DUKE_780
scans/DUKE_789
scans/DUKE_790
scans/DUKE_792
scans/DUKE_797
scans/DUKE_799
scans/DUKE_804
scans/DUKE_805
scans/DUKE_809
scans/DUKE_812
scans/DUKE_816
scans/DUKE_817
scans/DUKE_822
scans/DUKE_830
scans/DUKE_831
scans/DUKE_832
scans/DUKE_833
scans/DUKE_834
scans/DUKE_836
scans/DUKE_839
scans/DUKE_847
scans/DUKE_850
scans/DUKE_860
scans/DUKE_865
scans/DUKE_869
scans/DUKE_873
scans/DUKE_874
scans/DUKE_879
scans/DUKE_882
scans/DUKE_883
scans/DUKE_884
scans/DUKE_885
scans/DUKE_886
scans/DUKE_891
scans/DUKE_899
scans/DUKE_907
scans/DUKE_914
scans/DUKE_915
scans/DUKE_916
scans/DUKE_917
scans/ISPY1_1001
scans/ISPY1_1002
scans/ISPY1_1003
scans/ISPY1_1004
scans/ISPY1_1005
scans/ISPY1_1007
scans/ISPY1_1008
scans/ISPY1_1009
scans/ISPY1_1010
scans/ISPY1_1011
scans/ISPY1_1012
scans/ISPY1_1013
scans/ISPY1_1015
scans/ISPY1_1016
scans/ISPY1_1017
scans/ISPY1_1021
scans/ISPY1_1025
scans/ISPY1_1027
scans/ISPY1_1029
scans/ISPY1_1030
scans/ISPY1_1031
scans/ISPY1_1032
scans/ISPY1_1034
scans/ISPY1_1035
scans/ISPY1_1036
scans/ISPY1_1037
scans/ISPY1_1038
scans/ISPY1_1040
scans/ISPY1_1041
scans/ISPY1_1042
scans/ISPY1_1049
scans/ISPY1_1051
scans/ISPY1_1053
scans/ISPY1_1054
scans/ISPY1_1056
scans/ISPY1_1058
scans/ISPY1_1060
scans/ISPY1_1061
scans/ISPY1_1062
scans/ISPY1_1064
scans/ISPY1_1065
scans/ISPY1_1066
scans/ISPY1_1067
scans/ISPY1_1069
scans/ISPY1_1070
scans/ISPY1_1072
scans/ISPY1_1073
scans/ISPY1_1074
scans/ISPY1_1075
scans/ISPY1_1077
scans/ISPY1_1078
scans/ISPY1_1082
scans/ISPY1_1083
scans/ISPY1_1084
scans/ISPY1_1087
scans/ISPY1_1088
scans/ISPY1_1089
scans/ISPY1_1090
scans/ISPY1_1094
scans/ISPY1_1096
scans/ISPY1_1097
scans/ISPY1_1098
scans/ISPY1_1099
scans/ISPY1_1100
scans/ISPY1_1101
scans/ISPY1_1102
scans/ISPY1_1103
scans/ISPY1_1104
scans/ISPY1_1106
scans/ISPY1_1107
scans/ISPY1_1112
scans/ISPY1_1114
scans/ISPY1_1117
scans/ISPY1_1122
scans/ISPY1_1123
scans/ISPY1_1124
scans/ISPY1_1125
scans/ISPY1_1127
scans/ISPY1_1128
scans/ISPY1_1129
scans/ISPY1_1130
scans/ISPY1_1132
scans/ISPY1_1134
scans/ISPY1_1135
scans/ISPY1_1136
scans/ISPY1_1137
scans/ISPY1_1139
scans/ISPY1_1140
scans/ISPY1_1141
scans/ISPY1_1142
scans/ISPY1_1144
scans/ISPY1_1145
scans/ISPY1_1146
scans/ISPY1_1147
scans/ISPY1_1148
scans/ISPY1_1149
scans/ISPY1_1150
scans/ISPY1_1151
scans/ISPY1_1152
scans/ISPY1_1155
scans/ISPY1_1156
scans/ISPY1_1157
scans/ISPY1_1158
scans/ISPY1_1159
scans/ISPY1_1160
scans/ISPY1_1161
scans/ISPY1_1163
scans/ISPY1_1164
scans/ISPY1_1165
scans/ISPY1_1166
scans/ISPY1_1167
scans/ISPY1_1168
scans/ISPY1_1169
scans/ISPY1_1171
scans/ISPY1_1172
scans/ISPY1_1173
scans/ISPY1_1174
scans/ISPY1_1175
scans/ISPY1_1176
scans/ISPY1_1177
scans/ISPY1_1179
scans/ISPY1_1180
scans/ISPY1_1181
scans/ISPY1_1182
scans/ISPY1_1183
scans/ISPY1_1184
scans/ISPY1_1185
scans/ISPY1_1187
scans/ISPY1_1188
scans/ISPY1_1189
scans/ISPY1_1191
scans/ISPY1_1192
scans/ISPY1_1193
scans/ISPY1_1194
scans/ISPY1_1196
scans/ISPY1_1197
scans/ISPY1_1198
scans/ISPY1_1199
scans/ISPY1_1201
scans/ISPY1_1202
scans/ISPY1_1203
scans/ISPY1_1204
scans/ISPY1_1207
scans/ISPY1_1208
scans/ISPY1_1209
scans/ISPY1_1210
scans/ISPY1_1212
scans/ISPY1_1215
scans/ISPY1_1216
scans/ISPY1_1217
scans/ISPY1_1218
scans/ISPY1_1219
scans/ISPY1_1220
scans/ISPY1_1221
scans/ISPY1_1222
scans/ISPY1_1223
scans/ISPY1_1224
scans/ISPY1_1225
scans/ISPY1_1226
scans/ISPY1_1227
scans/ISPY1_1228
scans/ISPY1_1229
scans/ISPY1_1230
scans/ISPY1_1231
scans/ISPY1_1233
scans/ISPY1_1234
scans/ISPY1_1235
scans/ISPY1_1236
scans/ISPY1_1237
scans/ISPY1_1238
scans/ISPY1_1239
scans/ISPY2_100899
scans/ISPY2_102011
scans/ISPY2_102212
scans/ISPY2_103693
scans/ISPY2_103939
scans/ISPY2_104268
scans/ISPY2_104384
scans/ISPY2_105286
scans/ISPY2_105513
scans/ISPY2_107700
scans/ISPY2_108939
scans/ISPY2_108969
scans/ISPY2_109623
scans/ISPY2_109874
scans/ISPY2_109980
scans/ISPY2_111004
scans/ISPY2_111038
scans/ISPY2_111344
scans/ISPY2_111646
scans/ISPY2_111674
scans/ISPY2_111881
scans/ISPY2_112606
scans/ISPY2_114087
scans/ISPY2_115638
scans/ISPY2_115987
scans/ISPY2_116165
scans/ISPY2_116603
scans/ISPY2_117424
scans/ISPY2_117707
scans/ISPY2_118307
scans/ISPY2_119928
scans/ISPY2_120422
scans/ISPY2_122287
scans/ISPY2_122579
scans/ISPY2_122795
scans/ISPY2_123660
scans/ISPY2_125130
scans/ISPY2_125418
scans/ISPY2_127675
scans/ISPY2_127791
scans/ISPY2_128051
scans/ISPY2_128675
scans/ISPY2_129837
scans/ISPY2_129973
scans/ISPY2_130580
scans/ISPY2_130892
scans/ISPY2_131595
scans/ISPY2_131961
scans/ISPY2_132463
scans/ISPY2_133650
scans/ISPY2_134526
scans/ISPY2_136536
scans/ISPY2_138027
scans/ISPY2_138425
scans/ISPY2_139137
scans/ISPY2_139771
scans/ISPY2_139973
scans/ISPY2_141782
scans/ISPY2_142688
scans/ISPY2_144302
scans/ISPY2_145513
scans/ISPY2_145777
scans/ISPY2_146033
scans/ISPY2_146987
scans/ISPY2_147139
scans/ISPY2_148357
scans/ISPY2_149654
scans/ISPY2_150547
scans/ISPY2_151230
scans/ISPY2_151481
scans/ISPY2_151980
scans/ISPY2_152090
scans/ISPY2_152197
scans/ISPY2_153327
scans/ISPY2_153880
scans/ISPY2_154293
scans/ISPY2_155171
scans/ISPY2_156163
scans/ISPY2_157270
scans/ISPY2_157463
scans/ISPY2_159284
scans/ISPY2_159352
scans/ISPY2_160120
scans/ISPY2_162562
scans/ISPY2_164468
scans/ISPY2_165925
scans/ISPY2_166412
scans/ISPY2_166782
scans/ISPY2_167271
scans/ISPY2_168044
scans/ISPY2_169536
scans/ISPY2_169918
scans/ISPY2_172168
scans/ISPY2_172283
scans/ISPY2_172366
scans/ISPY2_174903
scans/ISPY2_174904
scans/ISPY2_177795
scans/ISPY2_178649
scans/ISPY2_178815
scans/ISPY2_179369
scans/ISPY2_179568
scans/ISPY2_180027
scans/ISPY2_180663
scans/ISPY2_181442
scans/ISPY2_181819
scans/ISPY2_182346
scans/ISPY2_183831
scans/ISPY2_188091
scans/ISPY2_188511
scans/ISPY2_188700
scans/ISPY2_190224
scans/ISPY2_192548
scans/ISPY2_194024
scans/ISPY2_196024
scans/ISPY2_196064
scans/ISPY2_197942
scans/ISPY2_198891
scans/ISPY2_199115
scans/ISPY2_199960
scans/ISPY2_200222
scans/ISPY2_201831
scans/ISPY2_201873
scans/ISPY2_202535
scans/ISPY2_202539
scans/ISPY2_202956
scans/ISPY2_203060
scans/ISPY2_203254
scans/ISPY2_204939
scans/ISPY2_208265
scans/ISPY2_208303
scans/ISPY2_208650
scans/ISPY2_209397
scans/ISPY2_209967
scans/ISPY2_211408
scans/ISPY2_212307
scans/ISPY2_213328
scans/ISPY2_213672
scans/ISPY2_213913
scans/ISPY2_215932
scans/ISPY2_218249
scans/ISPY2_218503
scans/ISPY2_219545
scans/ISPY2_220471
scans/ISPY2_220664
scans/ISPY2_220925
scans/ISPY2_221375
scans/ISPY2_221686
scans/ISPY2_222135
scans/ISPY2_223030
scans/ISPY2_223526
scans/ISPY2_225836
scans/ISPY2_227055
scans/ISPY2_227832
scans/ISPY2_227881
scans/ISPY2_228192
scans/ISPY2_228340
scans/ISPY2_229144
scans/ISPY2_229328
scans/ISPY2_229824
scans/ISPY2_231633
scans/ISPY2_233191
scans/ISPY2_233832
scans/ISPY2_233962
scans/ISPY2_234272
scans/ISPY2_234723
scans/ISPY2_235995
scans/ISPY2_236470
scans/ISPY2_237158
scans/ISPY2_238790
scans/ISPY2_239061
scans/ISPY2_239910
scans/ISPY2_240035
scans/ISPY2_240432
scans/ISPY2_240957
scans/ISPY2_241705
scans/ISPY2_241998
scans/ISPY2_242370
scans/ISPY2_243836
scans/ISPY2_245655
scans/ISPY2_246134
scans/ISPY2_247641
scans/ISPY2_248255
scans/ISPY2_250274
scans/ISPY2_252748
scans/ISPY2_253531
scans/ISPY2_254060
scans/ISPY2_254273
scans/ISPY2_255078
scans/ISPY2_255388
scans/ISPY2_255535
scans/ISPY2_255577
scans/ISPY2_257735
scans/ISPY2_259206
scans/ISPY2_259899
scans/ISPY2_261304
scans/ISPY2_262131
scans/ISPY2_263143
scans/ISPY2_264305
scans/ISPY2_264678
scans/ISPY2_266509
scans/ISPY2_266840
scans/ISPY2_267306
scans/ISPY2_268937
scans/ISPY2_269899
scans/ISPY2_273691
scans/ISPY2_273745
scans/ISPY2_275034
scans/ISPY2_275626
scans/ISPY2_277848
scans/ISPY2_277888
scans/ISPY2_279902
scans/ISPY2_280375
scans/ISPY2_282082
scans/ISPY2_282644
scans/ISPY2_282777
scans/ISPY2_283070
scans/ISPY2_284355
scans/ISPY2_284443
scans/ISPY2_284593
scans/ISPY2_285339
scans/ISPY2_286984
scans/ISPY2_287300
scans/ISPY2_287961
scans/ISPY2_289107
scans/ISPY2_289420
scans/ISPY2_290413
scans/ISPY2_291515
scans/ISPY2_293142
scans/ISPY2_294176
scans/ISPY2_294265
scans/ISPY2_294739
scans/ISPY2_296123
scans/ISPY2_296841
scans/ISPY2_298101
scans/ISPY2_299364
scans/ISPY2_299840
scans/ISPY2_299962
scans/ISPY2_300724
scans/ISPY2_301289
scans/ISPY2_301665
scans/ISPY2_301968
scans/ISPY2_303685
scans/ISPY2_303947
scans/ISPY2_306127
scans/ISPY2_306401
scans/ISPY2_307659
scans/ISPY2_309830
scans/ISPY2_311316
scans/ISPY2_311455
scans/ISPY2_313243
scans/ISPY2_313672
scans/ISPY2_316996
scans/ISPY2_317131
scans/ISPY2_317402
scans/ISPY2_317641
scans/ISPY2_318293
scans/ISPY2_318407
scans/ISPY2_318438
scans/ISPY2_318569
scans/ISPY2_319324
scans/ISPY2_320538
scans/ISPY2_323721
scans/ISPY2_324021
scans/ISPY2_326202
scans/ISPY2_326433
scans/ISPY2_327133
scans/ISPY2_327142
scans/ISPY2_327917
scans/ISPY2_328160
scans/ISPY2_329076
scans/ISPY2_329941
scans/ISPY2_330134
scans/ISPY2_331192
scans/ISPY2_332655
scans/ISPY2_333145
scans/ISPY2_335091
scans/ISPY2_335536
scans/ISPY2_340186
scans/ISPY2_341238
scans/ISPY2_342142
scans/ISPY2_342959
scans/ISPY2_342996
scans/ISPY2_343898
scans/ISPY2_345460
scans/ISPY2_345483
scans/ISPY2_345574
scans/ISPY2_345907
scans/ISPY2_347516
scans/ISPY2_348009
scans/ISPY2_349225
scans/ISPY2_349330
scans/ISPY2_349639
scans/ISPY2_350331
scans/ISPY2_353318
scans/ISPY2_355292
scans/ISPY2_355942
scans/ISPY2_356399
scans/ISPY2_356431
scans/ISPY2_356684
scans/ISPY2_357017
scans/ISPY2_357034
scans/ISPY2_360937
scans/ISPY2_361701
scans/ISPY2_362150
scans/ISPY2_362993
scans/ISPY2_363669
scans/ISPY2_366120
scans/ISPY2_367682
scans/ISPY2_369040
scans/ISPY2_371528
scans/ISPY2_373346
scans/ISPY2_373672
scans/ISPY2_374106
scans/ISPY2_374121
scans/ISPY2_375342
scans/ISPY2_375455
scans/ISPY2_376676
scans/ISPY2_377460
scans/ISPY2_378401
scans/ISPY2_378885
scans/ISPY2_380239
scans/ISPY2_380769
scans/ISPY2_380972
scans/ISPY2_382853
scans/ISPY2_383456
scans/ISPY2_384830
scans/ISPY2_386664
scans/ISPY2_388581
scans/ISPY2_391942
scans/ISPY2_395076
scans/ISPY2_395249
scans/ISPY2_395379
scans/ISPY2_396723
scans/ISPY2_397505
scans/ISPY2_399478
scans/ISPY2_401215
scans/ISPY2_402265
scans/ISPY2_402384
scans/ISPY2_405717
scans/ISPY2_406190
scans/ISPY2_407539
scans/ISPY2_408692
scans/ISPY2_409288
scans/ISPY2_410083
scans/ISPY2_411008
scans/ISPY2_411684
scans/ISPY2_411806
scans/ISPY2_411950
scans/ISPY2_412772
scans/ISPY2_413211
scans/ISPY2_413961
scans/ISPY2_414256
scans/ISPY2_414286
scans/ISPY2_414844
scans/ISPY2_414971
scans/ISPY2_415039
scans/ISPY2_416434
scans/ISPY2_417474
scans/ISPY2_417654
scans/ISPY2_418593
scans/ISPY2_419590
scans/ISPY2_420523
scans/ISPY2_421829
scans/ISPY2_421917
scans/ISPY2_422013
scans/ISPY2_422450
scans/ISPY2_422454
scans/ISPY2_423619
scans/ISPY2_423979
scans/ISPY2_424541
scans/ISPY2_425173
scans/ISPY2_426106
scans/ISPY2_427321
scans/ISPY2_429220
scans/ISPY2_430441
scans/ISPY2_431061
scans/ISPY2_432114
scans/ISPY2_433144
scans/ISPY2_435279
scans/ISPY2_435313
scans/ISPY2_436371
scans/ISPY2_437162
scans/ISPY2_437968
scans/ISPY2_439489
scans/ISPY2_442637
scans/ISPY2_442669
scans/ISPY2_442981
scans/ISPY2_443444
scans/ISPY2_443708
scans/ISPY2_446263
scans/ISPY2_451482
scans/ISPY2_451816
scans/ISPY2_452703
scans/ISPY2_453596
scans/ISPY2_454808
scans/ISPY2_455828
scans/ISPY2_456432
scans/ISPY2_456506
scans/ISPY2_458196
scans/ISPY2_459311
scans/ISPY2_460642
scans/ISPY2_460776
scans/ISPY2_460812
scans/ISPY2_461824
scans/ISPY2_462581
scans/ISPY2_462582
scans/ISPY2_462605
scans/ISPY2_464547
scans/ISPY2_465008
scans/ISPY2_466267
scans/ISPY2_467622
scans/ISPY2_467686
scans/ISPY2_472799
scans/ISPY2_473365
scans/ISPY2_473468
scans/ISPY2_473505
scans/ISPY2_474874
scans/ISPY2_477816
scans/ISPY2_477994
scans/ISPY2_478055
scans/ISPY2_478484
scans/ISPY2_478655
scans/ISPY2_479417
scans/ISPY2_483667
scans/ISPY2_483910
scans/ISPY2_484867
scans/ISPY2_484894
scans/ISPY2_485637
scans/ISPY2_489194
scans/ISPY2_489504
scans/ISPY2_489973
scans/ISPY2_490023
scans/ISPY2_490805
scans/ISPY2_491526
scans/ISPY2_491779
scans/ISPY2_492612
scans/ISPY2_493472
scans/ISPY2_493519
scans/ISPY2_493775
scans/ISPY2_494022
scans/ISPY2_494296
scans/ISPY2_494946
scans/ISPY2_495440
scans/ISPY2_496205
scans/ISPY2_497010
scans/ISPY2_498024
scans/ISPY2_498985
scans/ISPY2_500826
scans/ISPY2_501303
scans/ISPY2_502486
scans/ISPY2_503034
scans/ISPY2_504838
scans/ISPY2_506623
scans/ISPY2_507198
scans/ISPY2_507249
scans/ISPY2_509012
scans/ISPY2_510543
scans/ISPY2_511851
scans/ISPY2_515105
scans/ISPY2_515141
scans/ISPY2_515281
scans/ISPY2_515284
scans/ISPY2_515565
scans/ISPY2_516763
scans/ISPY2_516834
scans/ISPY2_517446
scans/ISPY2_517870
scans/ISPY2_518000
scans/ISPY2_518576
scans/ISPY2_519738
scans/ISPY2_520258
scans/ISPY2_520471
scans/ISPY2_520986
scans/ISPY2_521860
scans/ISPY2_522140
scans/ISPY2_524170
scans/ISPY2_527320
scans/ISPY2_527581
scans/ISPY2_528479
scans/ISPY2_528833
scans/ISPY2_530095
scans/ISPY2_531672
scans/ISPY2_531988
scans/ISPY2_532183
scans/ISPY2_535415
scans/ISPY2_535569
scans/ISPY2_535779
scans/ISPY2_536253
scans/ISPY2_539291
scans/ISPY2_539876
scans/ISPY2_539904
scans/ISPY2_540539
scans/ISPY2_541165
scans/ISPY2_542392
scans/ISPY2_543795
scans/ISPY2_547892
scans/ISPY2_549172
scans/ISPY2_550157
scans/ISPY2_550421
scans/ISPY2_551795
scans/ISPY2_552313
scans/ISPY2_552549
scans/ISPY2_553012
scans/ISPY2_553141
scans/ISPY2_554577
scans/ISPY2_555214
scans/ISPY2_559021
scans/ISPY2_559263
scans/ISPY2_563681
scans/ISPY2_563856
scans/ISPY2_564234
scans/ISPY2_564701
scans/ISPY2_566011
scans/ISPY2_567201
scans/ISPY2_567907
scans/ISPY2_568331
scans/ISPY2_568953
scans/ISPY2_570148
scans/ISPY2_570380
scans/ISPY2_570685
scans/ISPY2_570966
scans/ISPY2_571276
scans/ISPY2_571995
scans/ISPY2_572016
scans/ISPY2_572235
scans/ISPY2_572444
scans/ISPY2_572731
scans/ISPY2_572793
scans/ISPY2_573586
scans/ISPY2_573605
scans/ISPY2_573881
scans/ISPY2_573919
scans/ISPY2_574091
scans/ISPY2_575372
scans/ISPY2_575457
scans/ISPY2_578975
scans/ISPY2_579881
scans/ISPY2_580541
scans/ISPY2_580632
scans/ISPY2_581648
scans/ISPY2_584561
scans/ISPY2_586091
scans/ISPY2_586207
scans/ISPY2_587388
scans/ISPY2_587604
scans/ISPY2_587691
scans/ISPY2_589502
scans/ISPY2_590220
scans/ISPY2_590299
scans/ISPY2_591079
scans/ISPY2_591180
scans/ISPY2_591810
scans/ISPY2_592535
scans/ISPY2_596079
scans/ISPY2_596458
scans/ISPY2_597253
scans/ISPY2_597873
scans/ISPY2_597907
scans/ISPY2_598798
scans/ISPY2_598835
scans/ISPY2_600536
scans/ISPY2_601489
scans/ISPY2_602451
scans/ISPY2_602943
scans/ISPY2_604199
scans/ISPY2_604326
scans/ISPY2_604380
scans/ISPY2_605713
scans/ISPY2_607047
scans/ISPY2_607843
scans/ISPY2_609151
scans/ISPY2_609642
scans/ISPY2_609897
scans/ISPY2_611662
scans/ISPY2_613188
scans/ISPY2_613961
scans/ISPY2_614044
scans/ISPY2_614434
scans/ISPY2_615873
scans/ISPY2_616994
scans/ISPY2_618240
scans/ISPY2_618717
scans/ISPY2_618860
scans/ISPY2_621179
scans/ISPY2_622078
scans/ISPY2_622315
scans/ISPY2_622688
scans/ISPY2_623086
scans/ISPY2_623569
scans/ISPY2_624777
scans/ISPY2_625800
scans/ISPY2_625854
scans/ISPY2_627118
scans/ISPY2_627981
scans/ISPY2_628692
scans/ISPY2_628788
scans/ISPY2_628823
scans/ISPY2_629210
scans/ISPY2_629371
scans/ISPY2_629606
scans/ISPY2_630758
scans/ISPY2_631299
scans/ISPY2_631337
scans/ISPY2_632408
scans/ISPY2_635632
scans/ISPY2_635862
scans/ISPY2_636424
scans/ISPY2_637051
scans/ISPY2_637566
scans/ISPY2_637752
scans/ISPY2_638126
scans/ISPY2_639663
scans/ISPY2_640043
scans/ISPY2_640463
scans/ISPY2_640927
scans/ISPY2_641246
scans/ISPY2_641697
scans/ISPY2_641977
scans/ISPY2_644186
scans/ISPY2_644609
scans/ISPY2_646233
scans/ISPY2_646600
scans/ISPY2_649198
scans/ISPY2_650589
scans/ISPY2_651145
scans/ISPY2_651401
scans/ISPY2_651541
scans/ISPY2_652480
scans/ISPY2_653325
scans/ISPY2_653927
scans/ISPY2_654021
scans/ISPY2_654064
scans/ISPY2_654956
scans/ISPY2_655128
scans/ISPY2_655703
scans/ISPY2_655795
scans/ISPY2_658541
scans/ISPY2_660534
scans/ISPY2_660915
scans/ISPY2_661730
scans/ISPY2_663144
scans/ISPY2_663197
scans/ISPY2_663467
scans/ISPY2_664111
scans/ISPY2_664658
scans/ISPY2_666147
scans/ISPY2_666450
scans/ISPY2_666715
scans/ISPY2_668752
scans/ISPY2_672734
scans/ISPY2_674897
scans/ISPY2_676048
scans/ISPY2_676365
scans/ISPY2_676630
scans/ISPY2_677910
scans/ISPY2_677915
scans/ISPY2_679787
scans/ISPY2_680881
scans/ISPY2_683173
scans/ISPY2_683374
scans/ISPY2_683457
scans/ISPY2_683896
scans/ISPY2_685182
scans/ISPY2_685753
scans/ISPY2_685795
scans/ISPY2_687288
scans/ISPY2_687733
scans/ISPY2_688291

In [45]:
scan_path_pattern = config.scan_path_pattern

# [id for id in metadata_df['patient_id'].to_list()]

metadata_df['patient_id'].apply(lambda patient_id: Path(f"{config.datasource}_{config.dataset}") / "images" / scan_path_pattern.format(patient_id=patient_id))

# [scan_path_pattern.format(id) for id in 
# metadata_df['patient_id']

0       BCN-AIM_MAMA-MIA/images/scans/DUKE_001
1       BCN-AIM_MAMA-MIA/images/scans/DUKE_002
2       BCN-AIM_MAMA-MIA/images/scans/DUKE_005
3       BCN-AIM_MAMA-MIA/images/scans/DUKE_009
4       BCN-AIM_MAMA-MIA/images/scans/DUKE_010
                         ...
1501     BCN-AIM_MAMA-MIA/images/scans/NACT_64
1502     BCN-AIM_MAMA-MIA/images/scans/NACT_65
1503     BCN-AIM_MAMA-MIA/images/scans/NACT_66
1504     BCN-AIM_MAMA-MIA/images/scans/NACT_67
1505     BCN-AIM_MAMA-MIA/images/scans/NACT_68
Name: patient_id, Length: 1506, dtype: object

In [25]:
scan_path = config.scan_path_pattern

for idx, row in metadata_df.iterrows():
    patient_id = row.patient_id
    print(scan_path.format(patient_id=patient_id))

scans/DUKE_001
scans/DUKE_002
scans/DUKE_005
scans/DUKE_009
scans/DUKE_010
scans/DUKE_012
scans/DUKE_019
scans/DUKE_021
scans/DUKE_022
scans/DUKE_028
scans/DUKE_032
scans/DUKE_034
scans/DUKE_040
scans/DUKE_041
scans/DUKE_043
scans/DUKE_044
scans/DUKE_045
scans/DUKE_046
scans/DUKE_048
scans/DUKE_051
scans/DUKE_055
scans/DUKE_057
scans/DUKE_059
scans/DUKE_060
scans/DUKE_061
scans/DUKE_064
scans/DUKE_069
scans/DUKE_071
scans/DUKE_077
scans/DUKE_082
scans/DUKE_086
scans/DUKE_090
scans/DUKE_091
scans/DUKE_097
scans/DUKE_099
scans/DUKE_101
scans/DUKE_103
scans/DUKE_104
scans/DUKE_105
scans/DUKE_107
scans/DUKE_114
scans/DUKE_115
scans/DUKE_116
scans/DUKE_117
scans/DUKE_119
scans/DUKE_120
scans/DUKE_123
scans/DUKE_129
scans/DUKE_132
scans/DUKE_134
scans/DUKE_136
scans/DUKE_137
scans/DUKE_141
scans/DUKE_142
scans/DUKE_144
scans/DUKE_148
scans/DUKE_150
scans/DUKE_156
scans/DUKE_157
scans/DUKE_160
scans/DUKE_163
scans/DUKE_167
scans/DUKE_168
scans/DUKE_176
scans/DUKE_177
scans/DUKE_178
scans/DUKE_180
scans/DUKE_183
scans/DUKE_185
scans/DUKE_189
scans/DUKE_192
scans/DUKE_198
scans/DUKE_202
scans/DUKE_205
scans/DUKE_211
scans/DUKE_217
scans/DUKE_218
scans/DUKE_225
scans/DUKE_228
scans/DUKE_233
scans/DUKE_234
scans/DUKE_236
scans/DUKE_237
scans/DUKE_239
scans/DUKE_240
scans/DUKE_244
scans/DUKE_250
scans/DUKE_253
scans/DUKE_255
scans/DUKE_256
scans/DUKE_258
scans/DUKE_260
scans/DUKE_265
scans/DUKE_268
scans/DUKE_269
scans/DUKE_271
scans/DUKE_275
scans/DUKE_282
scans/DUKE_283
scans/DUKE_285
scans/DUKE_287
scans/DUKE_290
scans/DUKE_293
scans/DUKE_298
scans/DUKE_301
scans/DUKE_303
scans/DUKE_304
scans/DUKE_306
scans/DUKE_307
scans/DUKE_313
scans/DUKE_317
scans/DUKE_321
scans/DUKE_323
scans/DUKE_328
scans/DUKE_333
scans/DUKE_335
scans/DUKE_338
scans/DUKE_345
scans/DUKE_346
scans/DUKE_350
scans/DUKE_353
scans/DUKE_356
scans/DUKE_360
scans/DUKE_363
scans/DUKE_368
scans/DUKE_377
scans/DUKE_378
scans/DUKE_383
scans/DUKE_385
scans/DUKE_386
scans/DUKE_387
scans/DUKE_395
scans/DUKE_397
scans/DUKE_398
scans/DUKE_399
scans/DUKE_400
scans/DUKE_406
scans/DUKE_407
scans/DUKE_408
scans/DUKE_412
scans/DUKE_414
scans/DUKE_420
scans/DUKE_424
scans/DUKE_428
scans/DUKE_429
scans/DUKE_431
scans/DUKE_435
scans/DUKE_437
scans/DUKE_438
scans/DUKE_441
scans/DUKE_444
scans/DUKE_454
scans/DUKE_457
scans/DUKE_464
scans/DUKE_465
scans/DUKE_468
scans/DUKE_470
scans/DUKE_474
scans/DUKE_480
scans/DUKE_482
scans/DUKE_486
scans/DUKE_489
scans/DUKE_491
scans/DUKE_501
scans/DUKE_506
scans/DUKE_507
scans/DUKE_508
scans/DUKE_512
scans/DUKE_514
scans/DUKE_517
scans/DUKE_521
scans/DUKE_525
scans/DUKE_527
scans/DUKE_530
scans/DUKE_534
scans/DUKE_535
scans/DUKE_539
scans/DUKE_541
scans/DUKE_543
scans/DUKE_545
scans/DUKE_546
scans/DUKE_552
scans/DUKE_558
scans/DUKE_559
scans/DUKE_560
scans/DUKE_562
scans/DUKE_567
scans/DUKE_568
scans/DUKE_573
scans/DUKE_577
scans/DUKE_585
scans/DUKE_590
scans/DUKE_592
scans/DUKE_595
scans/DUKE_597
scans/DUKE_605
scans/DUKE_607
scans/DUKE_609
scans/DUKE_610
scans/DUKE_612
scans/DUKE_614
scans/DUKE_615
scans/DUKE_616
scans/DUKE_618
scans/DUKE_623
scans/DUKE_633
scans/DUKE_636
scans/DUKE_640
scans/DUKE_641
scans/DUKE_642
scans/DUKE_645
scans/DUKE_650
scans/DUKE_651
scans/DUKE_652
scans/DUKE_656
scans/DUKE_660
scans/DUKE_662
scans/DUKE_663
scans/DUKE_666
scans/DUKE_670
scans/DUKE_672
scans/DUKE_677
scans/DUKE_679
scans/DUKE_681
scans/DUKE_684
scans/DUKE_685
scans/DUKE_686
scans/DUKE_687
scans/DUKE_688
scans/DUKE_691
scans/DUKE_693
scans/DUKE_694
scans/DUKE_697
scans/DUKE_710
scans/DUKE_717
scans/DUKE_718
scans/DUKE_723
scans/DUKE_724
scans/DUKE_725
scans/DUKE_735
scans/DUKE_746
scans/DUKE_751
scans/DUKE_754
scans/DUKE_757
scans/DUKE_758
scans/DUKE_762
scans/DUKE_765
scans/DUKE_774
scans/DUKE_775
scans/DUKE_776
scans/DUKE_778
scans/DUKE_780
scans/DUKE_789
scans/DUKE_790
scans/DUKE_792
scans/DUKE_797
scans/DUKE_799
scans/DUKE_804
scans/DUKE_805
scans/DUKE_809
scans/DUKE_812
scans/DUKE_816
scans/DUKE_817
scans/DUKE_822
scans/DUKE_830
scans/DUKE_831
scans/DUKE_832
scans/DUKE_833
scans/DUKE_834
scans/DUKE_836
scans/DUKE_839
scans/DUKE_847
scans/DUKE_850
scans/DUKE_860
scans/DUKE_865
scans/DUKE_869
scans/DUKE_873
scans/DUKE_874
scans/DUKE_879
scans/DUKE_882
scans/DUKE_883
scans/DUKE_884
scans/DUKE_885
scans/DUKE_886
scans/DUKE_891
scans/DUKE_899
scans/DUKE_907
scans/DUKE_914
scans/DUKE_915
scans/DUKE_916
scans/DUKE_917
scans/ISPY1_1001
scans/ISPY1_1002
scans/ISPY1_1003
scans/ISPY1_1004
scans/ISPY1_1005
scans/ISPY1_1007
scans/ISPY1_1008
scans/ISPY1_1009
scans/ISPY1_1010
scans/ISPY1_1011
scans/ISPY1_1012
scans/ISPY1_1013
scans/ISPY1_1015
scans/ISPY1_1016
scans/ISPY1_1017
scans/ISPY1_1021
scans/ISPY1_1025
scans/ISPY1_1027
scans/ISPY1_1029
scans/ISPY1_1030
scans/ISPY1_1031
scans/ISPY1_1032
scans/ISPY1_1034
scans/ISPY1_1035
scans/ISPY1_1036
scans/ISPY1_1037
scans/ISPY1_1038
scans/ISPY1_1040
scans/ISPY1_1041
scans/ISPY1_1042
scans/ISPY1_1049
scans/ISPY1_1051
scans/ISPY1_1053
scans/ISPY1_1054
scans/ISPY1_1056
scans/ISPY1_1058
scans/ISPY1_1060
scans/ISPY1_1061
scans/ISPY1_1062
scans/ISPY1_1064
scans/ISPY1_1065
scans/ISPY1_1066
scans/ISPY1_1067
scans/ISPY1_1069
scans/ISPY1_1070
scans/ISPY1_1072
scans/ISPY1_1073
scans/ISPY1_1074
scans/ISPY1_1075
scans/ISPY1_1077
scans/ISPY1_1078
scans/ISPY1_1082
scans/ISPY1_1083
scans/ISPY1_1084
scans/ISPY1_1087
scans/ISPY1_1088
scans/ISPY1_1089
scans/ISPY1_1090
scans/ISPY1_1094
scans/ISPY1_1096
scans/ISPY1_1097
scans/ISPY1_1098
scans/ISPY1_1099
scans/ISPY1_1100
scans/ISPY1_1101
scans/ISPY1_1102
scans/ISPY1_1103
scans/ISPY1_1104
scans/ISPY1_1106
scans/ISPY1_1107
scans/ISPY1_1112
scans/ISPY1_1114
scans/ISPY1_1117
scans/ISPY1_1122
scans/ISPY1_1123
scans/ISPY1_1124
scans/ISPY1_1125
scans/ISPY1_1127
scans/ISPY1_1128
scans/ISPY1_1129
scans/ISPY1_1130
scans/ISPY1_1132
scans/ISPY1_1134
scans/ISPY1_1135
scans/ISPY1_1136
scans/ISPY1_1137
scans/ISPY1_1139
scans/ISPY1_1140
scans/ISPY1_1141
scans/ISPY1_1142
scans/ISPY1_1144
scans/ISPY1_1145
scans/ISPY1_1146
scans/ISPY1_1147
scans/ISPY1_1148
scans/ISPY1_1149
scans/ISPY1_1150
scans/ISPY1_1151
scans/ISPY1_1152
scans/ISPY1_1155
scans/ISPY1_1156
scans/ISPY1_1157
scans/ISPY1_1158
scans/ISPY1_1159
scans/ISPY1_1160
scans/ISPY1_1161
scans/ISPY1_1163
scans/ISPY1_1164
scans/ISPY1_1165
scans/ISPY1_1166
scans/ISPY1_1167
scans/ISPY1_1168
scans/ISPY1_1169
scans/ISPY1_1171
scans/ISPY1_1172
scans/ISPY1_1173
scans/ISPY1_1174
scans/ISPY1_1175
scans/ISPY1_1176
scans/ISPY1_1177
scans/ISPY1_1179
scans/ISPY1_1180
scans/ISPY1_1181
scans/ISPY1_1182
scans/ISPY1_1183
scans/ISPY1_1184
scans/ISPY1_1185
scans/ISPY1_1187
scans/ISPY1_1188
scans/ISPY1_1189
scans/ISPY1_1191
scans/ISPY1_1192
scans/ISPY1_1193
scans/ISPY1_1194
scans/ISPY1_1196
scans/ISPY1_1197
scans/ISPY1_1198
scans/ISPY1_1199
scans/ISPY1_1201
scans/ISPY1_1202
scans/ISPY1_1203
scans/ISPY1_1204
scans/ISPY1_1207
scans/ISPY1_1208
scans/ISPY1_1209
scans/ISPY1_1210
scans/ISPY1_1212
scans/ISPY1_1215
scans/ISPY1_1216
scans/ISPY1_1217
scans/ISPY1_1218
scans/ISPY1_1219
scans/ISPY1_1220
scans/ISPY1_1221
scans/ISPY1_1222
scans/ISPY1_1223
scans/ISPY1_1224
scans/ISPY1_1225
scans/ISPY1_1226
scans/ISPY1_1227
scans/ISPY1_1228
scans/ISPY1_1229
scans/ISPY1_1230
scans/ISPY1_1231
scans/ISPY1_1233
scans/ISPY1_1234
scans/ISPY1_1235
scans/ISPY1_1236
scans/ISPY1_1237
scans/ISPY1_1238
scans/ISPY1_1239
scans/ISPY2_100899
scans/ISPY2_102011
scans/ISPY2_102212
scans/ISPY2_103693
scans/ISPY2_103939
scans/ISPY2_104268
scans/ISPY2_104384
scans/ISPY2_105286
scans/ISPY2_105513
scans/ISPY2_107700
scans/ISPY2_108939
scans/ISPY2_108969
scans/ISPY2_109623
scans/ISPY2_109874
scans/ISPY2_109980
scans/ISPY2_111004
scans/ISPY2_111038
scans/ISPY2_111344
scans/ISPY2_111646
scans/ISPY2_111674
scans/ISPY2_111881
scans/ISPY2_112606
scans/ISPY2_114087
scans/ISPY2_115638
scans/ISPY2_115987
scans/ISPY2_116165
scans/ISPY2_116603
scans/ISPY2_117424
scans/ISPY2_117707
scans/ISPY2_118307
scans/ISPY2_119928
scans/ISPY2_120422
scans/ISPY2_122287
scans/ISPY2_122579
scans/ISPY2_122795
scans/ISPY2_123660
scans/ISPY2_125130
scans/ISPY2_125418
scans/ISPY2_127675
scans/ISPY2_127791
scans/ISPY2_128051
scans/ISPY2_128675
scans/ISPY2_129837
scans/ISPY2_129973
scans/ISPY2_130580
scans/ISPY2_130892
scans/ISPY2_131595
scans/ISPY2_131961
scans/ISPY2_132463
scans/ISPY2_133650
scans/ISPY2_134526
scans/ISPY2_136536
scans/ISPY2_138027
scans/ISPY2_138425
scans/ISPY2_139137
scans/ISPY2_139771
scans/ISPY2_139973
scans/ISPY2_141782
scans/ISPY2_142688
scans/ISPY2_144302
scans/ISPY2_145513
scans/ISPY2_145777
scans/ISPY2_146033
scans/ISPY2_146987
scans/ISPY2_147139
scans/ISPY2_148357
scans/ISPY2_149654
scans/ISPY2_150547
scans/ISPY2_151230
scans/ISPY2_151481
scans/ISPY2_151980
scans/ISPY2_152090
scans/ISPY2_152197
scans/ISPY2_153327
scans/ISPY2_153880
scans/ISPY2_154293
scans/ISPY2_155171
scans/ISPY2_156163
scans/ISPY2_157270
scans/ISPY2_157463
scans/ISPY2_159284
scans/ISPY2_159352
scans/ISPY2_160120
scans/ISPY2_162562
scans/ISPY2_164468
scans/ISPY2_165925
scans/ISPY2_166412
scans/ISPY2_166782
scans/ISPY2_167271
scans/ISPY2_168044
scans/ISPY2_169536
scans/ISPY2_169918
scans/ISPY2_172168
scans/ISPY2_172283
scans/ISPY2_172366
scans/ISPY2_174903
scans/ISPY2_174904
scans/ISPY2_177795
scans/ISPY2_178649
scans/ISPY2_178815
scans/ISPY2_179369
scans/ISPY2_179568
scans/ISPY2_180027
scans/ISPY2_180663
scans/ISPY2_181442
scans/ISPY2_181819
scans/ISPY2_182346
scans/ISPY2_183831
scans/ISPY2_188091
scans/ISPY2_188511
scans/ISPY2_188700
scans/ISPY2_190224
scans/ISPY2_192548
scans/ISPY2_194024
scans/ISPY2_196024
scans/ISPY2_196064
scans/ISPY2_197942
scans/ISPY2_198891
scans/ISPY2_199115
scans/ISPY2_199960
scans/ISPY2_200222
scans/ISPY2_201831
scans/ISPY2_201873
scans/ISPY2_202535
scans/ISPY2_202539
scans/ISPY2_202956
scans/ISPY2_203060
scans/ISPY2_203254
scans/ISPY2_204939
scans/ISPY2_208265
scans/ISPY2_208303
scans/ISPY2_208650
scans/ISPY2_209397
scans/ISPY2_209967
scans/ISPY2_211408
scans/ISPY2_212307
scans/ISPY2_213328
scans/ISPY2_213672
scans/ISPY2_213913
scans/ISPY2_215932
scans/ISPY2_218249
scans/ISPY2_218503
scans/ISPY2_219545
scans/ISPY2_220471
scans/ISPY2_220664
scans/ISPY2_220925
scans/ISPY2_221375
scans/ISPY2_221686
scans/ISPY2_222135
scans/ISPY2_223030
scans/ISPY2_223526
scans/ISPY2_225836
scans/ISPY2_227055
scans/ISPY2_227832
scans/ISPY2_227881
scans/ISPY2_228192
scans/ISPY2_228340
scans/ISPY2_229144
scans/ISPY2_229328
scans/ISPY2_229824
scans/ISPY2_231633
scans/ISPY2_233191
scans/ISPY2_233832
scans/ISPY2_233962
scans/ISPY2_234272
scans/ISPY2_234723
scans/ISPY2_235995
scans/ISPY2_236470
scans/ISPY2_237158
scans/ISPY2_238790
scans/ISPY2_239061
scans/ISPY2_239910
scans/ISPY2_240035
scans/ISPY2_240432
scans/ISPY2_240957
scans/ISPY2_241705
scans/ISPY2_241998
scans/ISPY2_242370
scans/ISPY2_243836
scans/ISPY2_245655
scans/ISPY2_246134
scans/ISPY2_247641
scans/ISPY2_248255
scans/ISPY2_250274
scans/ISPY2_252748
scans/ISPY2_253531
scans/ISPY2_254060
scans/ISPY2_254273
scans/ISPY2_255078
scans/ISPY2_255388
scans/ISPY2_255535
scans/ISPY2_255577
scans/ISPY2_257735
scans/ISPY2_259206
scans/ISPY2_259899
scans/ISPY2_261304
scans/ISPY2_262131
scans/ISPY2_263143
scans/ISPY2_264305
scans/ISPY2_264678
scans/ISPY2_266509
scans/ISPY2_266840
scans/ISPY2_267306
scans/ISPY2_268937
scans/ISPY2_269899
scans/ISPY2_273691
scans/ISPY2_273745
scans/ISPY2_275034
scans/ISPY2_275626
scans/ISPY2_277848
scans/ISPY2_277888
scans/ISPY2_279902
scans/ISPY2_280375
scans/ISPY2_282082
scans/ISPY2_282644
scans/ISPY2_282777
scans/ISPY2_283070
scans/ISPY2_284355
scans/ISPY2_284443
scans/ISPY2_284593
scans/ISPY2_285339
scans/ISPY2_286984
scans/ISPY2_287300
scans/ISPY2_287961
scans/ISPY2_289107
scans/ISPY2_289420
scans/ISPY2_290413
scans/ISPY2_291515
scans/ISPY2_293142
scans/ISPY2_294176
scans/ISPY2_294265
scans/ISPY2_294739
scans/ISPY2_296123
scans/ISPY2_296841
scans/ISPY2_298101
scans/ISPY2_299364
scans/ISPY2_299840
scans/ISPY2_299962
scans/ISPY2_300724
scans/ISPY2_301289
scans/ISPY2_301665
scans/ISPY2_301968
scans/ISPY2_303685
scans/ISPY2_303947
scans/ISPY2_306127
scans/ISPY2_306401
scans/ISPY2_307659
scans/ISPY2_309830
scans/ISPY2_311316
scans/ISPY2_311455
scans/ISPY2_313243
scans/ISPY2_313672
scans/ISPY2_316996
scans/ISPY2_317131
scans/ISPY2_317402
scans/ISPY2_317641
scans/ISPY2_318293
scans/ISPY2_318407
scans/ISPY2_318438
scans/ISPY2_318569
scans/ISPY2_319324
scans/ISPY2_320538
scans/ISPY2_323721
scans/ISPY2_324021
scans/ISPY2_326202
scans/ISPY2_326433
scans/ISPY2_327133
scans/ISPY2_327142
scans/ISPY2_327917
scans/ISPY2_328160
scans/ISPY2_329076
scans/ISPY2_329941
scans/ISPY2_330134
scans/ISPY2_331192
scans/ISPY2_332655
scans/ISPY2_333145
scans/ISPY2_335091
scans/ISPY2_335536
scans/ISPY2_340186
scans/ISPY2_341238
scans/ISPY2_342142
scans/ISPY2_342959
scans/ISPY2_342996
scans/ISPY2_343898
scans/ISPY2_345460
scans/ISPY2_345483
scans/ISPY2_345574
scans/ISPY2_345907
scans/ISPY2_347516
scans/ISPY2_348009
scans/ISPY2_349225
scans/ISPY2_349330
scans/ISPY2_349639
scans/ISPY2_350331
scans/ISPY2_353318
scans/ISPY2_355292
scans/ISPY2_355942
scans/ISPY2_356399
scans/ISPY2_356431
scans/ISPY2_356684
scans/ISPY2_357017
scans/ISPY2_357034
scans/ISPY2_360937
scans/ISPY2_361701
scans/ISPY2_362150
scans/ISPY2_362993
scans/ISPY2_363669
scans/ISPY2_366120
scans/ISPY2_367682
scans/ISPY2_369040
scans/ISPY2_371528
scans/ISPY2_373346
scans/ISPY2_373672
scans/ISPY2_374106
scans/ISPY2_374121
scans/ISPY2_375342
scans/ISPY2_375455
scans/ISPY2_376676
scans/ISPY2_377460
scans/ISPY2_378401
scans/ISPY2_378885
scans/ISPY2_380239
scans/ISPY2_380769
scans/ISPY2_380972
scans/ISPY2_382853
scans/ISPY2_383456
scans/ISPY2_384830
scans/ISPY2_386664
scans/ISPY2_388581
scans/ISPY2_391942
scans/ISPY2_395076
scans/ISPY2_395249
scans/ISPY2_395379
scans/ISPY2_396723
scans/ISPY2_397505
scans/ISPY2_399478
scans/ISPY2_401215
scans/ISPY2_402265
scans/ISPY2_402384
scans/ISPY2_405717
scans/ISPY2_406190
scans/ISPY2_407539
scans/ISPY2_408692
scans/ISPY2_409288
scans/ISPY2_410083
scans/ISPY2_411008
scans/ISPY2_411684
scans/ISPY2_411806
scans/ISPY2_411950
scans/ISPY2_412772
scans/ISPY2_413211
scans/ISPY2_413961
scans/ISPY2_414256
scans/ISPY2_414286
scans/ISPY2_414844
scans/ISPY2_414971
scans/ISPY2_415039
scans/ISPY2_416434
scans/ISPY2_417474
scans/ISPY2_417654
scans/ISPY2_418593
scans/ISPY2_419590
scans/ISPY2_420523
scans/ISPY2_421829
scans/ISPY2_421917
scans/ISPY2_422013
scans/ISPY2_422450
scans/ISPY2_422454
scans/ISPY2_423619
scans/ISPY2_423979
scans/ISPY2_424541
scans/ISPY2_425173
scans/ISPY2_426106
scans/ISPY2_427321
scans/ISPY2_429220
scans/ISPY2_430441
scans/ISPY2_431061
scans/ISPY2_432114
scans/ISPY2_433144
scans/ISPY2_435279
scans/ISPY2_435313
scans/ISPY2_436371
scans/ISPY2_437162
scans/ISPY2_437968
scans/ISPY2_439489
scans/ISPY2_442637
scans/ISPY2_442669
scans/ISPY2_442981
scans/ISPY2_443444
scans/ISPY2_443708
scans/ISPY2_446263
scans/ISPY2_451482
scans/ISPY2_451816
scans/ISPY2_452703
scans/ISPY2_453596
scans/ISPY2_454808
scans/ISPY2_455828
scans/ISPY2_456432
scans/ISPY2_456506
scans/ISPY2_458196
scans/ISPY2_459311
scans/ISPY2_460642
scans/ISPY2_460776
scans/ISPY2_460812
scans/ISPY2_461824
scans/ISPY2_462581
scans/ISPY2_462582
scans/ISPY2_462605
scans/ISPY2_464547
scans/ISPY2_465008
scans/ISPY2_466267
scans/ISPY2_467622
scans/ISPY2_467686
scans/ISPY2_472799
scans/ISPY2_473365
scans/ISPY2_473468
scans/ISPY2_473505
scans/ISPY2_474874
scans/ISPY2_477816
scans/ISPY2_477994
scans/ISPY2_478055
scans/ISPY2_478484
scans/ISPY2_478655
scans/ISPY2_479417
scans/ISPY2_483667
scans/ISPY2_483910
scans/ISPY2_484867
scans/ISPY2_484894
scans/ISPY2_485637
scans/ISPY2_489194
scans/ISPY2_489504
scans/ISPY2_489973
scans/ISPY2_490023
scans/ISPY2_490805
scans/ISPY2_491526
scans/ISPY2_491779
scans/ISPY2_492612
scans/ISPY2_493472
scans/ISPY2_493519
scans/ISPY2_493775
scans/ISPY2_494022
scans/ISPY2_494296
scans/ISPY2_494946
scans/ISPY2_495440
scans/ISPY2_496205
scans/ISPY2_497010
scans/ISPY2_498024
scans/ISPY2_498985
scans/ISPY2_500826
scans/ISPY2_501303
scans/ISPY2_502486
scans/ISPY2_503034
scans/ISPY2_504838
scans/ISPY2_506623
scans/ISPY2_507198
scans/ISPY2_507249
scans/ISPY2_509012
scans/ISPY2_510543
scans/ISPY2_511851
scans/ISPY2_515105
scans/ISPY2_515141
scans/ISPY2_515281
scans/ISPY2_515284
scans/ISPY2_515565
scans/ISPY2_516763
scans/ISPY2_516834
scans/ISPY2_517446
scans/ISPY2_517870
scans/ISPY2_518000
scans/ISPY2_518576
scans/ISPY2_519738
scans/ISPY2_520258
scans/ISPY2_520471
scans/ISPY2_520986
scans/ISPY2_521860
scans/ISPY2_522140
scans/ISPY2_524170
scans/ISPY2_527320
scans/ISPY2_527581
scans/ISPY2_528479
scans/ISPY2_528833
scans/ISPY2_530095
scans/ISPY2_531672
scans/ISPY2_531988
scans/ISPY2_532183
scans/ISPY2_535415
scans/ISPY2_535569
scans/ISPY2_535779
scans/ISPY2_536253
scans/ISPY2_539291
scans/ISPY2_539876
scans/ISPY2_539904
scans/ISPY2_540539
scans/ISPY2_541165
scans/ISPY2_542392
scans/ISPY2_543795
scans/ISPY2_547892
scans/ISPY2_549172
scans/ISPY2_550157
scans/ISPY2_550421
scans/ISPY2_551795
scans/ISPY2_552313
scans/ISPY2_552549
scans/ISPY2_553012
scans/ISPY2_553141
scans/ISPY2_554577
scans/ISPY2_555214
scans/ISPY2_559021
scans/ISPY2_559263
scans/ISPY2_563681
scans/ISPY2_563856
scans/ISPY2_564234
scans/ISPY2_564701
scans/ISPY2_566011
scans/ISPY2_567201
scans/ISPY2_567907
scans/ISPY2_568331
scans/ISPY2_568953
scans/ISPY2_570148
scans/ISPY2_570380
scans/ISPY2_570685
scans/ISPY2_570966
scans/ISPY2_571276
scans/ISPY2_571995
scans/ISPY2_572016
scans/ISPY2_572235
scans/ISPY2_572444
scans/ISPY2_572731
scans/ISPY2_572793
scans/ISPY2_573586
scans/ISPY2_573605
scans/ISPY2_573881
scans/ISPY2_573919
scans/ISPY2_574091
scans/ISPY2_575372
scans/ISPY2_575457
scans/ISPY2_578975
scans/ISPY2_579881
scans/ISPY2_580541
scans/ISPY2_580632
scans/ISPY2_581648
scans/ISPY2_584561
scans/ISPY2_586091
scans/ISPY2_586207
scans/ISPY2_587388
scans/ISPY2_587604
scans/ISPY2_587691
scans/ISPY2_589502
scans/ISPY2_590220
scans/ISPY2_590299
scans/ISPY2_591079
scans/ISPY2_591180
scans/ISPY2_591810
scans/ISPY2_592535
scans/ISPY2_596079
scans/ISPY2_596458
scans/ISPY2_597253
scans/ISPY2_597873
scans/ISPY2_597907
scans/ISPY2_598798
scans/ISPY2_598835
scans/ISPY2_600536
scans/ISPY2_601489
scans/ISPY2_602451
scans/ISPY2_602943
scans/ISPY2_604199
scans/ISPY2_604326
scans/ISPY2_604380
scans/ISPY2_605713
scans/ISPY2_607047
scans/ISPY2_607843
scans/ISPY2_609151
scans/ISPY2_609642
scans/ISPY2_609897
scans/ISPY2_611662
scans/ISPY2_613188
scans/ISPY2_613961
scans/ISPY2_614044
scans/ISPY2_614434
scans/ISPY2_615873
scans/ISPY2_616994
scans/ISPY2_618240
scans/ISPY2_618717
scans/ISPY2_618860
scans/ISPY2_621179
scans/ISPY2_622078
scans/ISPY2_622315
scans/ISPY2_622688
scans/ISPY2_623086
scans/ISPY2_623569
scans/ISPY2_624777
scans/ISPY2_625800
scans/ISPY2_625854
scans/ISPY2_627118
scans/ISPY2_627981
scans/ISPY2_628692
scans/ISPY2_628788
scans/ISPY2_628823
scans/ISPY2_629210
scans/ISPY2_629371
scans/ISPY2_629606
scans/ISPY2_630758
scans/ISPY2_631299
scans/ISPY2_631337
scans/ISPY2_632408
scans/ISPY2_635632
scans/ISPY2_635862
scans/ISPY2_636424
scans/ISPY2_637051
scans/ISPY2_637566
scans/ISPY2_637752
scans/ISPY2_638126
scans/ISPY2_639663
scans/ISPY2_640043
scans/ISPY2_640463
scans/ISPY2_640927
scans/ISPY2_641246
scans/ISPY2_641697
scans/ISPY2_641977
scans/ISPY2_644186
scans/ISPY2_644609
scans/ISPY2_646233
scans/ISPY2_646600
scans/ISPY2_649198
scans/ISPY2_650589
scans/ISPY2_651145
scans/ISPY2_651401
scans/ISPY2_651541
scans/ISPY2_652480
scans/ISPY2_653325
scans/ISPY2_653927
scans/ISPY2_654021
scans/ISPY2_654064
scans/ISPY2_654956
scans/ISPY2_655128
scans/ISPY2_655703
scans/ISPY2_655795
scans/ISPY2_658541
scans/ISPY2_660534
scans/ISPY2_660915
scans/ISPY2_661730
scans/ISPY2_663144
scans/ISPY2_663197
scans/ISPY2_663467
scans/ISPY2_664111
scans/ISPY2_664658
scans/ISPY2_666147
scans/ISPY2_666450
scans/ISPY2_666715
scans/ISPY2_668752
scans/ISPY2_672734
scans/ISPY2_674897
scans/ISPY2_676048
scans/ISPY2_676365
scans/ISPY2_676630
scans/ISPY2_677910
scans/ISPY2_677915
scans/ISPY2_679787
scans/ISPY2_680881
scans/ISPY2_683173
scans/ISPY2_683374
scans/ISPY2_683457
scans/ISPY2_683896
scans/ISPY2_685182
scans/ISPY2_685753
scans/ISPY2_685795
scans/ISPY2_687288
scans/ISPY2_687733
scans/ISPY2_688291

In [ ]:
metadata_df.patient_id.apply(lambda row: f"{config.scan_path_pattern}")

0       scans/{patient_id}
1       scans/{patient_id}
2       scans/{patient_id}
3       scans/{patient_id}
4       scans/{patient_id}
               ...
1501    scans/{patient_id}
1502    scans/{patient_id}
1503    scans/{patient_id}
1504    scans/{patient_id}
1505    scans/{patient_id}
Name: patient_id, Length: 1506, dtype: object

In [ ]:
metadata_df

,patient_id,dataset,bilateral_breast_cancer,multifocal_cancer,nac_agent,endocrine_therapy,anti_her2_neu_therapy,pcr,mastectomy_post_nac,days_to_follow_up,...,scanner_model,high_bit,window_center,window_width,echo_time,repetition_time,acquisition_times,acquisition_date,tcia_series_uid,raw_scan_path
0,DUKE_001,DUKE,0,0.0,NaN,0.0,1.0,0.0,0.0,2940.0,...,Avanto,11,53.0,145.0,1.360,4.120,"[0, 584, 714, 846, 977]",NaN,1.3.6.1.4.1.14519.5.2.1.1857778498036652445367...,NaN
1,DUKE_002,DUKE,0,0.0,NaN,0.0,0.0,0.0,0.0,1649.0,...,Signa HDxt,15,326.0,652.0,2.704,6.918,"[0, 165, 288, 411]",NaN,1.3.6.1.4.1.14519.5.2.1.2920879504444133146439...,NaN
2,DUKE_005,DUKE,0,1.0,NaN,0.0,1.0,1.0,1.0,1845.0,...,Avanto,11,106.0,288.0,1.340,4.270,"[0, 183, 289, 398]",NaN,1.3.6.1.4.1.14519.5.2.1.3082672827908226352755...,NaN
3,DUKE_009,DUKE,0,1.0,NaN,0.0,0.0,1.0,0.0,1554.0,...,Signa HDxt,15,231.0,462.0,2.604,6.032,"[0, 199, 314, 429]",NaN,1.3.6.1.4.1.14519.5.2.1.1955995935901349215652...,NaN
4,DUKE_010,DUKE,0,1.0,NaN,0.0,0.0,0.0,1.0,384.0,...,Signa HDxt,15,532.0,1064.0,2.436,5.668,"[0, 156, 255, 355]",NaN,1.3.6.1.4.1.14519.5.2.1.1390661710325525999628...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1501,NACT_64,NACT,0,0.0,FEC100,NaN,NaN,0.0,1.0,705.0,...,GENESIS_SIGNA,15,15.0,31.0,4.200,8.400,"[0, 403, 751]",1994/02/23,1.3.6.1.4.1.14519.5.2.1.7695.2311.188949018082...,NaN
1502,NACT_65,NACT,0,0.0,Anthracycline,NaN,NaN,0.0,1.0,1448.0,...,GENESIS_SIGNA,15,34.0,68.0,4.200,8.000,"[0, 380, 686]",1992/06/16,1.3.6.1.4.1.14519.5.2.1.7695.2311.196765391224...,NaN
1503,NACT_66,NACT,0,0.0,Anthracycline,NaN,NaN,0.0,0.0,667.0,...,GENESIS_SIGNA,15,32.0,64.0,4.200,8.000,"[0, 362, 678, 962]",1992/01/07,1.3.6.1.4.1.14519.5.2.1.7695.2311.757338311647...,NaN
1504,NACT_67,NACT,0,0.0,Anthracycline,NaN,NaN,0.0,1.0,1234.0,...,GENESIS_SIGNA,15,NaN,NaN,4.200,11.000,"[0, 441, 947]",1988/04/21,1.3.6.1.4.1.14519.5.2.1.7695.2311.298593028606...,NaN
1505,NACT_68,NACT,0,0.0,Anthracycline,NaN,NaN,0.0,0.0,1639.0,...,GENESIS_SIGNA,15,NaN,NaN,4.200,8.200,"[0, 361, 738]",1991/04/11,1.3.6.1.4.1.14519.5.2.1.7695.2311.189236515346...,NaN